local ns = dofile("harness.lua")
Login("WARRIOR", 10, { 2457, 78 })
check(SETTINGS_CATEGORY ~= nil, "settings page registered")
SlashCmdList.SPELLBOOKEXTENDED("options")
check(SETTINGS_OPENED == "Spellbook Extended", "/sbe options opens it")
SETTINGS_CATEGORY.frame:Show()
local items = ListState()
check(items[7386] and items[7386].entry.quest, "Sunder Armor is a quest spell")
check(items[355] and items[355].entry.quest, "Taunt is a quest spell")
done()
