-- Generated by tools/build_data.py. Do not edit by hand.
-- Forever client build 1.60.1.69876.
local _, SBE = ...

SBE.Data.DRUID = {
    tabs = { "Balance", "Feral Combat", "Restoration" },
    spells = {
        { id = 1126, level = 1, tab = 3, rank = 1, cost = 10 }, -- Mark of the Wild 1
        { id = 8921, level = 4, tab = 1, rank = 1, cost = 100 }, -- Moonfire 1
        { id = 774, level = 4, tab = 3, rank = 1, cost = 100 }, -- Rejuvenation 1
        { id = 467, level = 6, tab = 1, rank = 1, cost = 100 }, -- Thorns 1
        { id = 5177, level = 6, tab = 1, rank = 2, cost = 100, prev = 5176 }, -- Wrath 2
        { id = 339, level = 8, tab = 1, rank = 1, cost = 200 }, -- Entangling Roots 1
        { id = 5186, level = 8, tab = 3, rank = 2, cost = 200, prev = 5185 }, -- Healing Touch 2
        { id = 8924, level = 10, tab = 1, rank = 2, cost = 300, prev = 8921 }, -- Moonfire 2
        { id = 16689, level = 10, tab = 1, rank = 1 }, -- Nature's Grasp 1
        { id = 18960, level = 10, tab = 1 }, -- Teleport: Moonglade
        { id = 5487, level = 10, tab = 2, quest = true }, -- Bear Form
        { id = 99, level = 10, tab = 2, rank = 1, cost = 300, needs = { 5487 } }, -- Demoralizing Roar 1
        { id = 6795, level = 10, tab = 2, quest = true }, -- Growl
        { id = 6807, level = 10, tab = 2, rank = 1, quest = true }, -- Maul 1
        { id = 5232, level = 10, tab = 3, rank = 2, cost = 300, prev = 1126 }, -- Mark of the Wild 2
        { id = 1058, level = 10, tab = 3, rank = 2, cost = 300, prev = 774 }, -- Rejuvenation 2
        { id = 5229, level = 12, tab = 2, cost = 800, needs = { 5487 } }, -- Enrage
        { id = 8936, level = 12, tab = 3, rank = 1, cost = 800 }, -- Regrowth 1
        { id = 437138, level = 12, tab = 3, rank = 1 }, -- Revive 1
        { id = 782, level = 14, tab = 1, rank = 2, cost = 900, prev = 467 }, -- Thorns 2
        { id = 5178, level = 14, tab = 1, rank = 3, cost = 900, prev = 5177 }, -- Wrath 3
        { id = 5211, level = 14, tab = 2, rank = 1, cost = 900, needs = { 5487 } }, -- Bash 1
        { id = 8946, level = 14, tab = 3 }, -- Cure Poison
        { id = 5187, level = 14, tab = 3, rank = 3, cost = 900, prev = 5186 }, -- Healing Touch 3
        { id = 8925, level = 16, tab = 1, rank = 3, cost = 1800, prev = 8924 }, -- Moonfire 3
        { id = 1066, level = 16, tab = 2, quest = true }, -- Aquatic Form
        { id = 779, level = 16, tab = 2, rank = 1, cost = 1800, needs = { 5487 } }, -- Swipe 1
        { id = 1430, level = 16, tab = 3, rank = 3, cost = 1800, prev = 1058 }, -- Rejuvenation 3
        { id = 1062, level = 18, tab = 1, rank = 2, cost = 1900, prev = 339 }, -- Entangling Roots 2
        { id = 770, level = 18, tab = 1, rank = 1, cost = 1900 }, -- Faerie Fire 1
        { id = 2637, level = 18, tab = 1, rank = 1, cost = 1900 }, -- Hibernate 1
        { id = 16810, level = 18, tab = 1, rank = 2, prev = 16689 }, -- Nature's Grasp 2
        { id = 6808, level = 18, tab = 2, rank = 2, cost = 1900, prev = 6807 }, -- Maul 2
        { id = 8938, level = 18, tab = 3, rank = 2, cost = 1900, prev = 8936 }, -- Regrowth 2
        { id = 16864, level = 20, tab = 1 }, -- Omen of Clarity
        { id = 2912, level = 20, tab = 1, rank = 1, cost = 2000 }, -- Starfire 1
        { id = 768, level = 20, tab = 2, cost = 2000 }, -- Cat Form
        { id = 1082, level = 20, tab = 2, rank = 1, cost = 2000, needs = { 768 } }, -- Claw 1
        { id = 1735, level = 20, tab = 2, rank = 2, cost = 2000, prev = 99 }, -- Demoralizing Roar 2
        { id = 5215, level = 20, tab = 2, rank = 1, cost = 2000, needs = { 768 } }, -- Prowl 1
        { id = 1079, level = 20, tab = 2, rank = 1, cost = 2000, needs = { 768 } }, -- Rip 1
        { id = 5188, level = 20, tab = 3, rank = 4, cost = 2000, prev = 5187 }, -- Healing Touch 4
        { id = 6756, level = 20, tab = 3, rank = 3, cost = 2000, prev = 5232 }, -- Mark of the Wild 3
        { id = 20484, level = 20, tab = 3, rank = 1, cost = 2000 }, -- Rebirth 1
        { id = 8926, level = 22, tab = 1, rank = 4, cost = 3000, prev = 8925 }, -- Moonfire 4
        { id = 2908, level = 22, tab = 1, rank = 1, cost = 3000 }, -- Soothe Animal 1
        { id = 5179, level = 22, tab = 1, rank = 4, cost = 3000, prev = 5178 }, -- Wrath 4
        { id = 5221, level = 22, tab = 2, rank = 1, cost = 3000, needs = { 768 } }, -- Shred 1
        { id = 2090, level = 22, tab = 3, rank = 4, cost = 3000, prev = 1430 }, -- Rejuvenation 4
        { id = 1075, level = 24, tab = 1, rank = 3, cost = 4000, prev = 782 }, -- Thorns 3
        { id = 1822, level = 24, tab = 2, rank = 1, cost = 4000, needs = { 768 } }, -- Rake 1
        { id = 780, level = 24, tab = 2, rank = 2, cost = 4000, prev = 779 }, -- Swipe 2
        { id = 5217, level = 24, tab = 2, cost = 4000, needs = { 768 } }, -- Tiger's Fury
        { id = 8939, level = 24, tab = 3, rank = 3, cost = 4000, prev = 8938 }, -- Regrowth 3
        { id = 2782, level = 24, tab = 3, cost = 4000 }, -- Remove Curse
        { id = 1237948, level = 24, tab = 3, rank = 2, prev = 437138 }, -- Revive 2
        { id = 8949, level = 26, tab = 1, rank = 2, cost = 4500, prev = 2912 }, -- Starfire 2
        { id = 1850, level = 26, tab = 2, rank = 1, cost = 4500, needs = { 768 } }, -- Dash 1
        { id = 6809, level = 26, tab = 2, rank = 3, cost = 4500, prev = 6808 }, -- Maul 3
        { id = 2893, level = 26, tab = 3, cost = 4500 }, -- Abolish Poison
        { id = 5189, level = 26, tab = 3, rank = 5, cost = 4500, prev = 5188 }, -- Healing Touch 5
        { id = 5195, level = 28, tab = 1, rank = 3, cost = 5000, prev = 1062 }, -- Entangling Roots 3
        { id = 8927, level = 28, tab = 1, rank = 5, cost = 5000, prev = 8926 }, -- Moonfire 5
        { id = 16811, level = 28, tab = 1, rank = 3, prev = 16810 }, -- Nature's Grasp 3
        { id = 5209, level = 28, tab = 2, cost = 5000, needs = { 5487 } }, -- Challenging Roar
        { id = 3029, level = 28, tab = 2, rank = 2, cost = 5000, prev = 1082 }, -- Claw 2
        { id = 8998, level = 28, tab = 2, rank = 1, cost = 5000, needs = { 768 } }, -- Cower 1
        { id = 9492, level = 28, tab = 2, rank = 2, cost = 5000, prev = 1079 }, -- Rip 2
        { id = 2091, level = 28, tab = 3, rank = 5, cost = 5000, prev = 2090 }, -- Rejuvenation 5
        { id = 778, level = 30, tab = 1, rank = 2, cost = 6000, prev = 770 }, -- Faerie Fire 2
        { id = 24974, level = 30, tab = 1, rank = 2, cost = 300, prev = 5570, requires = 5570 }, -- Insect Swarm 2
        { id = 5180, level = 30, tab = 1, rank = 5, cost = 6000, prev = 5179 }, -- Wrath 5
        { id = 6798, level = 30, tab = 2, rank = 2, cost = 6000, prev = 5211 }, -- Bash 2
        { id = 6800, level = 30, tab = 2, rank = 2, cost = 6000, prev = 5221 }, -- Shred 2
        { id = 783, level = 30, tab = 2, cost = 6000 }, -- Travel Form
        { id = 5234, level = 30, tab = 3, rank = 4, cost = 6000, prev = 6756 }, -- Mark of the Wild 4
        { id = 20739, level = 30, tab = 3, rank = 2, cost = 6000, prev = 20484 }, -- Rebirth 2
        { id = 8940, level = 30, tab = 3, rank = 4, cost = 6000, prev = 8939 }, -- Regrowth 4
        { id = 740, level = 30, tab = 3, rank = 1, cost = 6000 }, -- Tranquility 1
        { id = 9490, level = 32, tab = 2, rank = 3, cost = 8000, prev = 1735 }, -- Demoralizing Roar 3
        { id = 22568, level = 32, tab = 2, rank = 1, cost = 8000, needs = { 768 } }, -- Ferocious Bite 1
        { id = 6785, level = 32, tab = 2, rank = 1, cost = 8000, needs = { 768 } }, -- Ravage 1
        { id = 5225, level = 32, tab = 2, cost = 8000 }, -- Track Humanoids
        { id = 6778, level = 32, tab = 3, rank = 6, cost = 8000, prev = 5189 }, -- Healing Touch 6
        { id = 8928, level = 34, tab = 1, rank = 6, cost = 10000, prev = 8927 }, -- Moonfire 6
        { id = 8950, level = 34, tab = 1, rank = 3, cost = 10000, prev = 8949 }, -- Starfire 3
        { id = 8914, level = 34, tab = 1, rank = 4, cost = 10000, prev = 1075 }, -- Thorns 4
        { id = 8972, level = 34, tab = 2, rank = 4, cost = 10000, prev = 6809 }, -- Maul 4
        { id = 1823, level = 34, tab = 2, rank = 2, cost = 10000, prev = 1822 }, -- Rake 2
        { id = 769, level = 34, tab = 2, rank = 3, cost = 10000, prev = 780 }, -- Swipe 3
        { id = 3627, level = 34, tab = 3, rank = 6, cost = 10000, prev = 2091 }, -- Rejuvenation 6
        { id = 22842, level = 36, tab = 2, cost = 11000, needs = { 5487 } }, -- Frenzied Regeneration
        { id = 1238069, level = 36, tab = 2, rank = 2, prev = 407995, requires = 407995 }, -- Mangle 2
        { id = 9005, level = 36, tab = 2, rank = 1, cost = 11000, needs = { 768 } }, -- Pounce 1
        { id = 9493, level = 36, tab = 2, rank = 3, cost = 11000, prev = 9492 }, -- Rip 3
        { id = 8941, level = 36, tab = 3, rank = 5, cost = 11000, prev = 8940 }, -- Regrowth 5
        { id = 1237949, level = 36, tab = 3, rank = 3, prev = 1237948 }, -- Revive 3
        { id = 5196, level = 38, tab = 1, rank = 4, cost = 12000, prev = 5195 }, -- Entangling Roots 4
        { id = 18657, level = 38, tab = 1, rank = 2, cost = 12000, prev = 2637 }, -- Hibernate 2
        { id = 16812, level = 38, tab = 1, rank = 4, prev = 16811 }, -- Nature's Grasp 4
        { id = 8955, level = 38, tab = 1, rank = 2, cost = 12000, prev = 2908 }, -- Soothe Animal 2
        { id = 6780, level = 38, tab = 1, rank = 6, cost = 12000, prev = 5180 }, -- Wrath 6
        { id = 5201, level = 38, tab = 2, rank = 3, cost = 12000, prev = 3029 }, -- Claw 3
        { id = 8992, level = 38, tab = 2, rank = 3, cost = 12000, prev = 6800 }, -- Shred 3
        { id = 8903, level = 38, tab = 3, rank = 7, cost = 12000, prev = 6778 }, -- Healing Touch 7
        { id = 16914, level = 40, tab = 1, rank = 1, cost = 14000 }, -- Hurricane 1
        { id = 24975, level = 40, tab = 1, rank = 3, cost = 700, prev = 24974, requires = 5570 }, -- Insect Swarm 3
        { id = 8929, level = 40, tab = 1, rank = 7, cost = 14000, prev = 8928 }, -- Moonfire 7
        { id = 9000, level = 40, tab = 2, rank = 2, cost = 14000, prev = 8998 }, -- Cower 2
        { id = 9634, level = 40, tab = 2, cost = 14000, needs = { 5487 } }, -- Dire Bear Form
        { id = 20719, level = 40, tab = 2, cost = 14000, needs = { 768 } }, -- Feline Grace
        { id = 22827, level = 40, tab = 2, rank = 2, cost = 14000, prev = 22568 }, -- Ferocious Bite 2
        { id = 6783, level = 40, tab = 2, rank = 2, cost = 14000, prev = 5215 }, -- Prowl 2
        { id = 29166, level = 40, tab = 3, cost = 14000 }, -- Innervate
        { id = 8907, level = 40, tab = 3, rank = 5, cost = 14000, prev = 5234 }, -- Mark of the Wild 5
        { id = 20742, level = 40, tab = 3, rank = 3, cost = 14000, prev = 20739 }, -- Rebirth 3
        { id = 8910, level = 40, tab = 3, rank = 7, cost = 14000, prev = 3627 }, -- Rejuvenation 7
        { id = 8918, level = 40, tab = 3, rank = 2, cost = 14000, prev = 740 }, -- Tranquility 2
        { id = 9749, level = 42, tab = 1, rank = 3, cost = 16000, prev = 778 }, -- Faerie Fire 3
        { id = 8951, level = 42, tab = 1, rank = 4, cost = 16000, prev = 8950 }, -- Starfire 4
        { id = 9747, level = 42, tab = 2, rank = 4, cost = 16000, prev = 9490 }, -- Demoralizing Roar 4
        { id = 414644, level = 42, tab = 2, rank = 1 }, -- Lacerate 1
        { id = 9745, level = 42, tab = 2, rank = 5, cost = 16000, prev = 8972 }, -- Maul 5
        { id = 6787, level = 42, tab = 2, rank = 2, cost = 16000, prev = 6785 }, -- Ravage 2
        { id = 9750, level = 42, tab = 3, rank = 6, cost = 16000, prev = 8941 }, -- Regrowth 6
        { id = 22812, level = 44, tab = 1, cost = 18000 }, -- Barkskin
        { id = 9756, level = 44, tab = 1, rank = 5, cost = 18000, prev = 8914 }, -- Thorns 5
        { id = 1824, level = 44, tab = 2, rank = 3, cost = 18000, prev = 1823 }, -- Rake 3
        { id = 9752, level = 44, tab = 2, rank = 4, cost = 18000, prev = 9493 }, -- Rip 4
        { id = 9754, level = 44, tab = 2, rank = 4, cost = 18000, prev = 769 }, -- Swipe 4
        { id = 9758, level = 44, tab = 3, rank = 8, cost = 18000, prev = 8903 }, -- Healing Touch 8
        { id = 9833, level = 46, tab = 1, rank = 8, cost = 20000, prev = 8929 }, -- Moonfire 8
        { id = 8905, level = 46, tab = 1, rank = 7, cost = 20000, prev = 6780 }, -- Wrath 7
        { id = 8983, level = 46, tab = 2, rank = 3, cost = 20000, prev = 6798 }, -- Bash 3
        { id = 9821, level = 46, tab = 2, rank = 2, cost = 20000, prev = 1850 }, -- Dash 2
        { id = 9823, level = 46, tab = 2, rank = 2, cost = 20000, prev = 9005 }, -- Pounce 2
        { id = 9829, level = 46, tab = 2, rank = 4, cost = 20000, prev = 8992 }, -- Shred 4
        { id = 9839, level = 46, tab = 3, rank = 8, cost = 20000, prev = 8910 }, -- Rejuvenation 8
        { id = 9852, level = 48, tab = 1, rank = 5, cost = 22000, prev = 5196 }, -- Entangling Roots 5
        { id = 16813, level = 48, tab = 1, rank = 5, prev = 16812 }, -- Nature's Grasp 5
        { id = 9849, level = 48, tab = 2, rank = 4, cost = 22000, prev = 5201 }, -- Claw 4
        { id = 22828, level = 48, tab = 2, rank = 3, cost = 22000, prev = 22827 }, -- Ferocious Bite 3
        { id = 1238070, level = 48, tab = 2, rank = 3, prev = 1238069, requires = 407995 }, -- Mangle 3
        { id = 9856, level = 48, tab = 3, rank = 7, cost = 22000, prev = 9750 }, -- Regrowth 7
        { id = 1237950, level = 48, tab = 3, rank = 4, prev = 1237949 }, -- Revive 4
        { id = 17401, level = 50, tab = 1, rank = 2, cost = 23000, prev = 16914 }, -- Hurricane 2
        { id = 24976, level = 50, tab = 1, rank = 4, cost = 1150, prev = 24975, requires = 5570 }, -- Insect Swarm 4
        { id = 9875, level = 50, tab = 1, rank = 5, cost = 23000, prev = 8951 }, -- Starfire 5
        { id = 1235826, level = 50, tab = 2, rank = 2, prev = 414644 }, -- Lacerate 2
        { id = 9880, level = 50, tab = 2, rank = 6, cost = 23000, prev = 9745 }, -- Maul 6
        { id = 9866, level = 50, tab = 2, rank = 3, cost = 23000, prev = 6787 }, -- Ravage 3
        { id = 21849, level = 50, tab = 3, rank = 1, book = 17682 }, -- Gift of the Wild 1
        { id = 9888, level = 50, tab = 3, rank = 9, cost = 23000, prev = 9758 }, -- Healing Touch 9
        { id = 9884, level = 50, tab = 3, rank = 6, cost = 23000, prev = 8907 }, -- Mark of the Wild 6
        { id = 20747, level = 50, tab = 3, rank = 4, cost = 23000, prev = 20742 }, -- Rebirth 4
        { id = 9862, level = 50, tab = 3, rank = 3, cost = 23000, prev = 8918 }, -- Tranquility 3
        { id = 1238214, level = 50, tab = 3, rank = 2, prev = 408120, requires = 408120 }, -- Wild Growth 2
        { id = 9834, level = 52, tab = 1, rank = 9, cost = 26000, prev = 9833 }, -- Moonfire 9
        { id = 9892, level = 52, tab = 2, rank = 3, cost = 26000, prev = 9000 }, -- Cower 3
        { id = 9898, level = 52, tab = 2, rank = 5, cost = 26000, prev = 9747 }, -- Demoralizing Roar 5
        { id = 9894, level = 52, tab = 2, rank = 5, cost = 26000, prev = 9752 }, -- Rip 5
        { id = 9840, level = 52, tab = 3, rank = 9, cost = 26000, prev = 9839 }, -- Rejuvenation 9
        { id = 9907, level = 54, tab = 1, rank = 4, cost = 28000, prev = 9749 }, -- Faerie Fire 4
        { id = 9901, level = 54, tab = 1, rank = 3, cost = 28000, prev = 8955 }, -- Soothe Animal 3
        { id = 9910, level = 54, tab = 1, rank = 6, cost = 28000, prev = 9756 }, -- Thorns 6
        { id = 9912, level = 54, tab = 1, rank = 8, cost = 28000, prev = 8905 }, -- Wrath 8
        { id = 9904, level = 54, tab = 2, rank = 4, cost = 28000, prev = 1824 }, -- Rake 4
        { id = 9830, level = 54, tab = 2, rank = 5, cost = 28000, prev = 9829 }, -- Shred 5
        { id = 9908, level = 54, tab = 2, rank = 5, cost = 28000, prev = 9754 }, -- Swipe 5
        { id = 9857, level = 54, tab = 3, rank = 8, cost = 28000, prev = 9856 }, -- Regrowth 8
        { id = 22829, level = 56, tab = 2, rank = 4, cost = 30000, prev = 22828 }, -- Ferocious Bite 4
        { id = 9827, level = 56, tab = 2, rank = 3, cost = 30000, prev = 9823 }, -- Pounce 3
        { id = 9889, level = 56, tab = 3, rank = 10, cost = 30000, prev = 9888 }, -- Healing Touch 10
        { id = 9853, level = 58, tab = 1, rank = 6, cost = 32000, prev = 9852 }, -- Entangling Roots 6
        { id = 18658, level = 58, tab = 1, rank = 3, cost = 32000, prev = 18657 }, -- Hibernate 3
        { id = 9835, level = 58, tab = 1, rank = 10, cost = 32000, prev = 9834 }, -- Moonfire 10
        { id = 17329, level = 58, tab = 1, rank = 6, prev = 16813 }, -- Nature's Grasp 6
        { id = 9876, level = 58, tab = 1, rank = 6, cost = 32000, prev = 9875 }, -- Starfire 6
        { id = 9850, level = 58, tab = 2, rank = 5, cost = 32000, prev = 9849 }, -- Claw 5
        { id = 1235827, level = 58, tab = 2, rank = 3, prev = 1235826 }, -- Lacerate 3
        { id = 9881, level = 58, tab = 2, rank = 7, cost = 32000, prev = 9880 }, -- Maul 7
        { id = 9867, level = 58, tab = 2, rank = 4, cost = 32000, prev = 9866 }, -- Ravage 4
        { id = 9841, level = 58, tab = 3, rank = 10, cost = 32000, prev = 9840 }, -- Rejuvenation 10
        { id = 17402, level = 60, tab = 1, rank = 3, cost = 34000, prev = 17401 }, -- Hurricane 3
        { id = 24977, level = 60, tab = 1, rank = 5, cost = 1700, prev = 24976, requires = 5570 }, -- Insect Swarm 5
        { id = 25298, level = 60, tab = 1, rank = 7, book = 21295, prev = 9876 }, -- Starfire 7
        { id = 31018, level = 60, tab = 2, rank = 5, book = 24101, prev = 22829 }, -- Ferocious Bite 5
        { id = 1238073, level = 60, tab = 2, rank = 4, prev = 1238070, requires = 407995 }, -- Mangle 4
        { id = 9913, level = 60, tab = 2, rank = 3, cost = 34000, prev = 6783 }, -- Prowl 3
        { id = 9896, level = 60, tab = 2, rank = 6, cost = 34000, prev = 9894 }, -- Rip 6
        { id = 21850, level = 60, tab = 3, rank = 2, book = 17683, prev = 21849 }, -- Gift of the Wild 2
        { id = 25297, level = 60, tab = 3, rank = 11, book = 21294, prev = 9889 }, -- Healing Touch 11
        { id = 9885, level = 60, tab = 3, rank = 7, cost = 34000, prev = 9884 }, -- Mark of the Wild 7
        { id = 20748, level = 60, tab = 3, rank = 5, cost = 34000, prev = 20747 }, -- Rebirth 5
        { id = 9858, level = 60, tab = 3, rank = 9, cost = 34000, prev = 9857 }, -- Regrowth 9
        { id = 25299, level = 60, tab = 3, rank = 11, book = 21296, prev = 9841 }, -- Rejuvenation 11
        { id = 1237951, level = 60, tab = 3, rank = 5, prev = 1237950 }, -- Revive 5
        { id = 9863, level = 60, tab = 3, rank = 4, cost = 34000, prev = 9862 }, -- Tranquility 4
        { id = 1238215, level = 60, tab = 3, rank = 3, prev = 1238214, requires = 408120 }, -- Wild Growth 3
    },
}
