-- Generated by tools/build_data.py. Do not edit by hand.
-- Forever client build 1.60.1.69876.
local _, SBE = ...

SBE.Data.HUNTER = {
    tabs = { "Beast Mastery", "Marksmanship", "Survival" },
    spells = {
        { id = 1494, level = 1, tab = 3, cost = 10 }, -- Track Beasts
        { id = 13163, level = 4, tab = 1, cost = 100 }, -- Aspect of the Monkey
        { id = 1978, level = 4, tab = 2, rank = 1, cost = 100 }, -- Serpent Sting 1
        { id = 3044, level = 6, tab = 2, rank = 1, cost = 100 }, -- Arcane Shot 1
        { id = 1130, level = 6, tab = 2, rank = 1, cost = 100 }, -- Hunter's Mark 1
        { id = 5116, level = 8, tab = 2, cost = 200 }, -- Concussive Shot
        { id = 14260, level = 8, tab = 3, rank = 2, cost = 200, prev = 2973 }, -- Raptor Strike 2
        { id = 13165, level = 10, tab = 1, rank = 1, cost = 400 }, -- Aspect of the Hawk 1
        { id = 5149, level = 10, tab = 1, quest = true }, -- Beast Training
        { id = 883, level = 10, tab = 1, quest = true }, -- Call Pet
        { id = 2641, level = 10, tab = 1, quest = true }, -- Dismiss Pet
        { id = 6991, level = 10, tab = 1, quest = true }, -- Feed Pet
        { id = 982, level = 10, tab = 1, quest = true }, -- Revive Pet
        { id = 1515, level = 10, tab = 1, quest = true }, -- Tame Beast
        { id = 13549, level = 10, tab = 2, rank = 2, cost = 400, prev = 1978 }, -- Serpent Sting 2
        { id = 19883, level = 10, tab = 3, cost = 400 }, -- Track Humanoids
        { id = 136, level = 12, tab = 1, rank = 1, cost = 600, needs = { 1515 } }, -- Mend Pet 1
        { id = 14281, level = 12, tab = 2, rank = 2, cost = 600, prev = 3044 }, -- Arcane Shot 2
        { id = 20736, level = 12, tab = 2, rank = 1, cost = 600 }, -- Distracting Shot 1
        { id = 2974, level = 12, tab = 3, rank = 1, cost = 600 }, -- Wing Clip 1
        { id = 6197, level = 14, tab = 1, cost = 1200 }, -- Eagle Eye
        { id = 1002, level = 14, tab = 1, cost = 1200 }, -- Eyes of the Beast
        { id = 1513, level = 14, tab = 1, rank = 1, cost = 1200 }, -- Scare Beast 1
        { id = 13795, level = 16, tab = 3, rank = 1, cost = 1800 }, -- Immolation Trap 1
        { id = 1495, level = 16, tab = 3, rank = 1, cost = 1800 }, -- Mongoose Bite 1
        { id = 14261, level = 16, tab = 3, rank = 3, cost = 1800, prev = 14260 }, -- Raptor Strike 3
        { id = 14318, level = 18, tab = 1, rank = 2, cost = 2000, prev = 13165 }, -- Aspect of the Hawk 2
        { id = 2643, level = 18, tab = 2, rank = 1, cost = 2000 }, -- Multi-Shot 1
        { id = 13550, level = 18, tab = 2, rank = 3, cost = 2000, prev = 13549 }, -- Serpent Sting 3
        { id = 19884, level = 18, tab = 3, cost = 2000 }, -- Track Undead
        { id = 5118, level = 20, tab = 1, cost = 2200 }, -- Aspect of the Cheetah
        { id = 3111, level = 20, tab = 1, rank = 2, cost = 2200, prev = 136 }, -- Mend Pet 2
        { id = 19434, level = 20, tab = 2, rank = 1 }, -- Aimed Shot 1
        { id = 14282, level = 20, tab = 2, rank = 3, cost = 2200, prev = 14281 }, -- Arcane Shot 3
        { id = 14274, level = 20, tab = 2, rank = 2, cost = 2200, prev = 20736 }, -- Distracting Shot 2
        { id = 781, level = 20, tab = 3, rank = 1, cost = 2200 }, -- Disengage 1
        { id = 1499, level = 20, tab = 3, rank = 1, cost = 2200 }, -- Freezing Trap 1
        { id = 14323, level = 22, tab = 2, rank = 2, cost = 6000, prev = 1130 }, -- Hunter's Mark 2
        { id = 3043, level = 22, tab = 2, rank = 1, cost = 6000 }, -- Scorpid Sting 1
        { id = 1462, level = 24, tab = 1, cost = 7000 }, -- Beast Lore
        { id = 14262, level = 24, tab = 3, rank = 4, cost = 7000, prev = 14261 }, -- Raptor Strike 4
        { id = 19885, level = 24, tab = 3, cost = 7000 }, -- Track Hidden
        { id = 3045, level = 26, tab = 2, cost = 7000 }, -- Rapid Fire
        { id = 13551, level = 26, tab = 2, rank = 4, cost = 7000, prev = 13550 }, -- Serpent Sting 4
        { id = 14302, level = 26, tab = 3, rank = 2, cost = 7000, prev = 13795 }, -- Immolation Trap 2
        { id = 19880, level = 26, tab = 3, cost = 7000 }, -- Track Elementals
        { id = 14319, level = 28, tab = 1, rank = 3, cost = 8000, prev = 14318 }, -- Aspect of the Hawk 3
        { id = 3661, level = 28, tab = 1, rank = 3, cost = 8000, prev = 3111 }, -- Mend Pet 3
        { id = 20900, level = 28, tab = 2, rank = 2, prev = 19434 }, -- Aimed Shot 2
        { id = 14283, level = 28, tab = 2, rank = 4, cost = 8000, prev = 14282 }, -- Arcane Shot 4
        { id = 13809, level = 28, tab = 3, cost = 8000 }, -- Frost Trap
        { id = 13161, level = 30, tab = 1, rank = 1, cost = 8000 }, -- Aspect of the Beast 1
        { id = 14326, level = 30, tab = 1, rank = 2, cost = 8000, prev = 1513 }, -- Scare Beast 2
        { id = 15629, level = 30, tab = 2, rank = 3, cost = 8000, prev = 14274 }, -- Distracting Shot 3
        { id = 1242634, level = 30, tab = 3, rank = 2, prev = 19306, requires = 19306 }, -- Counterattack 2
        { id = 5384, level = 30, tab = 3, cost = 8000 }, -- Feign Death
        { id = 24118, level = 30, tab = 3, rank = 1 }, -- Lacerate 1
        { id = 14269, level = 30, tab = 3, rank = 2, cost = 8000, prev = 1495 }, -- Mongoose Bite 2
        { id = 1543, level = 32, tab = 2, cost = 10000 }, -- Flare
        { id = 1299348, level = 32, tab = 2, rank = 2, prev = 1299346, requires = 1299346 }, -- Trueshot Aura 2
        { id = 14263, level = 32, tab = 3, rank = 5, cost = 10000, prev = 14262 }, -- Raptor Strike 5
        { id = 19878, level = 32, tab = 3, cost = 10000 }, -- Track Demons
        { id = 13552, level = 34, tab = 2, rank = 5, cost = 12000, prev = 13551 }, -- Serpent Sting 5
        { id = 14272, level = 34, tab = 3, rank = 2, cost = 12000, prev = 781 }, -- Disengage 2
        { id = 13813, level = 34, tab = 3, rank = 1, cost = 12000 }, -- Explosive Trap 1
        { id = 3662, level = 36, tab = 1, rank = 4, cost = 14000, prev = 3661 }, -- Mend Pet 4
        { id = 1293525, level = 36, tab = 1, rank = 2, prev = 1293241, requires = 1293241 }, -- Summon Hawk 2
        { id = 20901, level = 36, tab = 2, rank = 3, prev = 20900 }, -- Aimed Shot 3
        { id = 14284, level = 36, tab = 2, rank = 5, cost = 14000, prev = 14283 }, -- Arcane Shot 5
        { id = 3034, level = 36, tab = 2, rank = 1, cost = 14000 }, -- Viper Sting 1
        { id = 14303, level = 36, tab = 3, rank = 3, cost = 14000, prev = 14302 }, -- Immolation Trap 3
        { id = 14320, level = 38, tab = 1, rank = 4, cost = 16000, prev = 14319 }, -- Aspect of the Hawk 4
        { id = 14267, level = 38, tab = 3, rank = 2, cost = 16000, prev = 2974 }, -- Wing Clip 2
        { id = 1299445, level = 40, tab = 1, rank = 2, prev = 13161 }, -- Aspect of the Beast 2
        { id = 13159, level = 40, tab = 1, cost = 18000 }, -- Aspect of the Pack
        { id = 15630, level = 40, tab = 2, rank = 4, cost = 18000, prev = 15629 }, -- Distracting Shot 4
        { id = 14324, level = 40, tab = 2, rank = 3, cost = 18000, prev = 14323 }, -- Hunter's Mark 3
        { id = 19506, level = 40, tab = 2, rank = 3, prev = 1299348, requires = 1299346 }, -- Trueshot Aura 3
        { id = 1510, level = 40, tab = 2, rank = 1, cost = 18000 }, -- Volley 1
        { id = 14310, level = 40, tab = 3, rank = 2, cost = 18000, prev = 1499 }, -- Freezing Trap 2
        { id = 24119, level = 40, tab = 3, rank = 2, prev = 24118 }, -- Lacerate 2
        { id = 14264, level = 40, tab = 3, rank = 6, cost = 18000, prev = 14263 }, -- Raptor Strike 6
        { id = 19882, level = 40, tab = 3, cost = 18000 }, -- Track Giants
        { id = 13553, level = 42, tab = 2, rank = 6, cost = 24000, prev = 13552 }, -- Serpent Sting 6
        { id = 20909, level = 42, tab = 3, rank = 3, cost = 1200, prev = 1242634, requires = 19306 }, -- Counterattack 3
        { id = 13542, level = 44, tab = 1, rank = 5, cost = 26000, prev = 3662 }, -- Mend Pet 5
        { id = 20902, level = 44, tab = 2, rank = 4, prev = 20901 }, -- Aimed Shot 4
        { id = 14285, level = 44, tab = 2, rank = 6, cost = 26000, prev = 14284 }, -- Arcane Shot 6
        { id = 14316, level = 44, tab = 3, rank = 2, cost = 26000, prev = 13813 }, -- Explosive Trap 2
        { id = 14270, level = 44, tab = 3, rank = 3, cost = 26000, prev = 14269 }, -- Mongoose Bite 3
        { id = 20043, level = 46, tab = 1, rank = 1, cost = 28000 }, -- Aspect of the Wild 1
        { id = 14327, level = 46, tab = 1, rank = 3, cost = 28000, prev = 14326 }, -- Scare Beast 3
        { id = 14279, level = 46, tab = 2, rank = 2, cost = 28000, prev = 3034 }, -- Viper Sting 2
        { id = 14304, level = 46, tab = 3, rank = 4, cost = 28000, prev = 14303 }, -- Immolation Trap 4
        { id = 14321, level = 48, tab = 1, rank = 5, cost = 32000, prev = 14320 }, -- Aspect of the Hawk 5
        { id = 1293526, level = 48, tab = 1, rank = 3, prev = 1293525, requires = 1293241 }, -- Summon Hawk 3
        { id = 1310785, level = 48, tab = 2, rank = 2, prev = 1310687, requires = 1310687 }, -- Sniper Shot 2
        { id = 14273, level = 48, tab = 3, rank = 3, cost = 32000, prev = 14272 }, -- Disengage 3
        { id = 14265, level = 48, tab = 3, rank = 7, cost = 32000, prev = 14264 }, -- Raptor Strike 7
        { id = 1299446, level = 50, tab = 1, rank = 3, prev = 1299445 }, -- Aspect of the Beast 3
        { id = 15631, level = 50, tab = 2, rank = 5, cost = 36000, prev = 15630 }, -- Distracting Shot 5
        { id = 13554, level = 50, tab = 2, rank = 7, cost = 36000, prev = 13553 }, -- Serpent Sting 7
        { id = 20905, level = 50, tab = 2, rank = 4, cost = 1800, prev = 19506, requires = 1299346 }, -- Trueshot Aura 4
        { id = 14294, level = 50, tab = 2, rank = 2, cost = 36000, prev = 1510 }, -- Volley 2
        { id = 24120, level = 50, tab = 3, rank = 3, prev = 24119 }, -- Lacerate 3
        { id = 19879, level = 50, tab = 3, cost = 36000 }, -- Track Dragonkin
        { id = 13543, level = 52, tab = 1, rank = 6, cost = 40000, prev = 13542 }, -- Mend Pet 6
        { id = 20903, level = 52, tab = 2, rank = 5, prev = 20902 }, -- Aimed Shot 5
        { id = 14286, level = 52, tab = 2, rank = 7, cost = 40000, prev = 14285 }, -- Arcane Shot 7
        { id = 20910, level = 54, tab = 3, rank = 4, cost = 2100, prev = 20909, requires = 19306 }, -- Counterattack 4
        { id = 14317, level = 54, tab = 3, rank = 3, cost = 42000, prev = 14316 }, -- Explosive Trap 3
        { id = 20190, level = 56, tab = 1, rank = 2, cost = 46000, prev = 20043 }, -- Aspect of the Wild 2
        { id = 14280, level = 56, tab = 2, rank = 3, cost = 46000, prev = 14279 }, -- Viper Sting 3
        { id = 14305, level = 56, tab = 3, rank = 5, cost = 46000, prev = 14304 }, -- Immolation Trap 5
        { id = 14266, level = 56, tab = 3, rank = 8, cost = 46000, prev = 14265 }, -- Raptor Strike 8
        { id = 14322, level = 58, tab = 1, rank = 6, cost = 48000, prev = 14321 }, -- Aspect of the Hawk 6
        { id = 14325, level = 58, tab = 2, rank = 4, cost = 48000, prev = 14324 }, -- Hunter's Mark 4
        { id = 13555, level = 58, tab = 2, rank = 8, cost = 48000, prev = 13554 }, -- Serpent Sting 8
        { id = 1310786, level = 58, tab = 2, rank = 3, prev = 1310785, requires = 1310687 }, -- Sniper Shot 3
        { id = 14295, level = 58, tab = 2, rank = 3, cost = 48000, prev = 14294 }, -- Volley 3
        { id = 14271, level = 58, tab = 3, rank = 4, cost = 48000, prev = 14270 }, -- Mongoose Bite 4
        { id = 1299447, level = 60, tab = 1, rank = 4, prev = 1299446 }, -- Aspect of the Beast 4
        { id = 25296, level = 60, tab = 1, rank = 7, book = 21307, prev = 14322 }, -- Aspect of the Hawk 7
        { id = 13544, level = 60, tab = 1, rank = 7, cost = 50000, prev = 13543 }, -- Mend Pet 7
        { id = 1293527, level = 60, tab = 1, rank = 4, prev = 1293526, requires = 1293241 }, -- Summon Hawk 4
        { id = 19801, level = 60, tab = 1, book = 16665 }, -- Tranquilizing Shot
        { id = 20904, level = 60, tab = 2, rank = 6, prev = 20903 }, -- Aimed Shot 6
        { id = 14287, level = 60, tab = 2, rank = 8, cost = 50000, prev = 14286 }, -- Arcane Shot 8
        { id = 15632, level = 60, tab = 2, rank = 6, cost = 50000, prev = 15631 }, -- Distracting Shot 6
        { id = 25295, level = 60, tab = 2, rank = 9, book = 21306, prev = 13555 }, -- Serpent Sting 9
        { id = 20906, level = 60, tab = 2, rank = 5, cost = 2500, prev = 20905, requires = 1299346 }, -- Trueshot Aura 5
        { id = 14311, level = 60, tab = 3, rank = 3, cost = 50000, prev = 14310 }, -- Freezing Trap 3
        { id = 1299332, level = 60, tab = 3, rank = 4, prev = 24120 }, -- Lacerate 4
        { id = 14268, level = 60, tab = 3, rank = 3, cost = 50000, prev = 14267 }, -- Wing Clip 3
    },
}
