-- Generated by tools/build_data.py. Do not edit by hand.
-- Forever client build 1.60.1.69876.
local _, SBE = ...

SBE.Data.MAGE = {
    tabs = { "Arcane", "Fire", "Frost" },
    spells = {
        { id = 1459, level = 1, tab = 1, rank = 1, cost = 10 }, -- Arcane Intellect 1
        { id = 5504, level = 4, tab = 1, rank = 1, cost = 100 }, -- Conjure Water 1
        { id = 116, level = 4, tab = 3, rank = 1, cost = 100 }, -- Frostbolt 1
        { id = 587, level = 6, tab = 1, rank = 1, cost = 100 }, -- Conjure Food 1
        { id = 2136, level = 6, tab = 2, rank = 1, cost = 100 }, -- Fire Blast 1
        { id = 143, level = 6, tab = 2, rank = 2, cost = 100, prev = 133 }, -- Fireball 2
        { id = 5143, level = 8, tab = 1, rank = 1, cost = 200 }, -- Arcane Missiles 1
        { id = 118, level = 8, tab = 1, rank = 1, cost = 200 }, -- Polymorph 1
        { id = 205, level = 8, tab = 3, rank = 2, cost = 200, prev = 116 }, -- Frostbolt 2
        { id = 5505, level = 10, tab = 1, rank = 2, cost = 400, prev = 5504 }, -- Conjure Water 2
        { id = 12355, level = 10, tab = 2 }, -- Impact
        { id = 7300, level = 10, tab = 3, rank = 2, cost = 400, prev = 168 }, -- Frost Armor 2
        { id = 122, level = 10, tab = 3, rank = 1, cost = 400 }, -- Frost Nova 1
        { id = 597, level = 12, tab = 1, rank = 2, cost = 600, prev = 587 }, -- Conjure Food 2
        { id = 604, level = 12, tab = 1, rank = 1, cost = 600 }, -- Dampen Magic 1
        { id = 130, level = 12, tab = 1, cost = 600 }, -- Slow Fall
        { id = 145, level = 12, tab = 2, rank = 3, cost = 600, prev = 143 }, -- Fireball 3
        { id = 1449, level = 14, tab = 1, rank = 1, cost = 900 }, -- Arcane Explosion 1
        { id = 1460, level = 14, tab = 1, rank = 2, cost = 900, prev = 1459 }, -- Arcane Intellect 2
        { id = 2137, level = 14, tab = 2, rank = 2, cost = 900, prev = 2136 }, -- Fire Blast 2
        { id = 837, level = 14, tab = 3, rank = 3, cost = 900, prev = 205 }, -- Frostbolt 3
        { id = 5144, level = 16, tab = 1, rank = 2, cost = 1500, prev = 5143 }, -- Arcane Missiles 2
        { id = 2120, level = 16, tab = 2, rank = 1, cost = 1500 }, -- Flamestrike 1
        { id = 1008, level = 18, tab = 1, rank = 1, cost = 1800 }, -- Amplify Magic 1
        { id = 475, level = 18, tab = 1, cost = 1800 }, -- Remove Lesser Curse
        { id = 3140, level = 18, tab = 2, rank = 4, cost = 1800, prev = 145 }, -- Fireball 4
        { id = 1953, level = 20, tab = 1, cost = 2000 }, -- Blink
        { id = 5506, level = 20, tab = 1, rank = 3, cost = 2000, prev = 5505 }, -- Conjure Water 3
        { id = 12051, level = 20, tab = 1, cost = 2000 }, -- Evocation
        { id = 1463, level = 20, tab = 1, rank = 1, cost = 2000 }, -- Mana Shield 1
        { id = 12824, level = 20, tab = 1, rank = 2, cost = 2000, prev = 118 }, -- Polymorph 2
        { id = 3562, level = 20, tab = 1, cost = 2000, faction = "Alliance" }, -- Teleport: Ironforge
        { id = 3567, level = 20, tab = 1, cost = 2000, faction = "Horde" }, -- Teleport: Orgrimmar
        { id = 3561, level = 20, tab = 1, cost = 2000, faction = "Alliance" }, -- Teleport: Stormwind
        { id = 3563, level = 20, tab = 1, cost = 2000, faction = "Horde" }, -- Teleport: Undercity
        { id = 543, level = 20, tab = 2, rank = 1, cost = 2000 }, -- Fire Ward 1
        { id = 10, level = 20, tab = 3, rank = 1, cost = 2000 }, -- Blizzard 1
        { id = 7301, level = 20, tab = 3, rank = 3, cost = 2000, prev = 7300 }, -- Frost Armor 3
        { id = 7322, level = 20, tab = 3, rank = 4, cost = 2000, prev = 837 }, -- Frostbolt 4
        { id = 8437, level = 22, tab = 1, rank = 2, cost = 3000, prev = 1449 }, -- Arcane Explosion 2
        { id = 990, level = 22, tab = 1, rank = 3, cost = 3000, prev = 597 }, -- Conjure Food 3
        { id = 2138, level = 22, tab = 2, rank = 3, cost = 3000, prev = 2137 }, -- Fire Blast 3
        { id = 2948, level = 22, tab = 2, rank = 1, cost = 3000 }, -- Scorch 1
        { id = 6143, level = 22, tab = 3, rank = 1, cost = 3000 }, -- Frost Ward 1
        { id = 5145, level = 24, tab = 1, rank = 3, cost = 4000, prev = 5144 }, -- Arcane Missiles 3
        { id = 2139, level = 24, tab = 1, cost = 4000 }, -- Counterspell
        { id = 8450, level = 24, tab = 1, rank = 2, cost = 4000, prev = 604 }, -- Dampen Magic 2
        { id = 8400, level = 24, tab = 2, rank = 5, cost = 4000, prev = 3140 }, -- Fireball 5
        { id = 2121, level = 24, tab = 2, rank = 2, cost = 4000, prev = 2120 }, -- Flamestrike 2
        { id = 12505, level = 24, tab = 2, rank = 2, cost = 200, prev = 11366, requires = 11366 }, -- Pyroblast 2
        { id = 120, level = 26, tab = 3, rank = 1, cost = 5000 }, -- Cone of Cold 1
        { id = 865, level = 26, tab = 3, rank = 2, cost = 5000, prev = 122 }, -- Frost Nova 2
        { id = 8406, level = 26, tab = 3, rank = 5, cost = 5000, prev = 7322 }, -- Frostbolt 5
        { id = 1461, level = 28, tab = 1, rank = 3, cost = 7000, prev = 1460 }, -- Arcane Intellect 3
        { id = 759, level = 28, tab = 1, cost = 7000 }, -- Conjure Mana Agate
        { id = 8494, level = 28, tab = 1, rank = 2, cost = 7000, prev = 1463 }, -- Mana Shield 2
        { id = 8444, level = 28, tab = 2, rank = 2, cost = 7000, prev = 2948 }, -- Scorch 2
        { id = 6141, level = 28, tab = 3, rank = 2, cost = 7000, prev = 10 }, -- Blizzard 2
        { id = 400640, level = 28, tab = 3, rank = 2, prev = 1312002, requires = 1312002 }, -- Ice Lance 2
        { id = 8455, level = 30, tab = 1, rank = 2, cost = 8000, prev = 1008 }, -- Amplify Magic 2
        { id = 1239696, level = 30, tab = 1, rank = 2, prev = 400574, requires = 400574 }, -- Arcane Blast 2
        { id = 8438, level = 30, tab = 1, rank = 3, cost = 8000, prev = 8437 }, -- Arcane Explosion 3
        { id = 6127, level = 30, tab = 1, rank = 4, cost = 8000, prev = 5506 }, -- Conjure Water 4
        { id = 3565, level = 30, tab = 1, cost = 8000, faction = "Alliance" }, -- Teleport: Darnassus
        { id = 3566, level = 30, tab = 1, cost = 8000, faction = "Horde" }, -- Teleport: Thunder Bluff
        { id = 8412, level = 30, tab = 2, rank = 4, cost = 8000, prev = 2138 }, -- Fire Blast 4
        { id = 8457, level = 30, tab = 2, rank = 2, cost = 8000, prev = 543 }, -- Fire Ward 2
        { id = 8401, level = 30, tab = 2, rank = 6, cost = 8000, prev = 8400 }, -- Fireball 6
        { id = 12522, level = 30, tab = 2, rank = 3, cost = 400, prev = 12505, requires = 11366 }, -- Pyroblast 3
        { id = 7302, level = 30, tab = 3, rank = 1, cost = 8000 }, -- Ice Armor 1
        { id = 8416, level = 32, tab = 1, rank = 4, cost = 10000, prev = 5145 }, -- Arcane Missiles 4
        { id = 6129, level = 32, tab = 1, rank = 4, cost = 10000, prev = 990 }, -- Conjure Food 4
        { id = 8422, level = 32, tab = 2, rank = 3, cost = 10000, prev = 2121 }, -- Flamestrike 3
        { id = 8461, level = 32, tab = 3, rank = 2, cost = 10000, prev = 6143 }, -- Frost Ward 2
        { id = 8407, level = 32, tab = 3, rank = 6, cost = 10000, prev = 8406 }, -- Frostbolt 6
        { id = 6117, level = 34, tab = 1, rank = 1, cost = 13000 }, -- Mage Armor 1
        { id = 8445, level = 34, tab = 2, rank = 3, cost = 12000, prev = 8444 }, -- Scorch 3
        { id = 8492, level = 34, tab = 3, rank = 2, cost = 12000, prev = 120 }, -- Cone of Cold 2
        { id = 1240044, level = 34, tab = 3, rank = 3, prev = 400640, requires = 1312002 }, -- Ice Lance 3
        { id = 8451, level = 36, tab = 1, rank = 3, cost = 15000, prev = 8450 }, -- Dampen Magic 3
        { id = 8495, level = 36, tab = 1, rank = 3, cost = 13000, prev = 8494 }, -- Mana Shield 3
        { id = 13018, level = 36, tab = 2, rank = 2, cost = 650, prev = 11113, requires = 11113 }, -- Blast Wave 2
        { id = 8402, level = 36, tab = 2, rank = 7, cost = 13000, prev = 8401 }, -- Fireball 7
        { id = 12523, level = 36, tab = 2, rank = 4, cost = 650, prev = 12522, requires = 11366 }, -- Pyroblast 4
        { id = 8427, level = 36, tab = 3, rank = 3, cost = 13000, prev = 6141 }, -- Blizzard 3
        { id = 8439, level = 38, tab = 1, rank = 4, cost = 14000, prev = 8438 }, -- Arcane Explosion 4
        { id = 3552, level = 38, tab = 1, cost = 14000, needs = { 759 } }, -- Conjure Mana Jade
        { id = 8413, level = 38, tab = 2, rank = 5, cost = 14000, prev = 8412 }, -- Fire Blast 5
        { id = 8408, level = 38, tab = 3, rank = 7, cost = 14000, prev = 8407 }, -- Frostbolt 7
        { id = 1239697, level = 40, tab = 1, rank = 3, prev = 1239696, requires = 400574 }, -- Arcane Blast 3
        { id = 8417, level = 40, tab = 1, rank = 5, cost = 15000, prev = 8416 }, -- Arcane Missiles 5
        { id = 10138, level = 40, tab = 1, rank = 5, cost = 15000, prev = 6127 }, -- Conjure Water 5
        { id = 12825, level = 40, tab = 1, rank = 3, cost = 15000, prev = 12824 }, -- Polymorph 3
        { id = 11416, level = 40, tab = 1, cost = 13500, faction = "Alliance" }, -- Portal: Ironforge
        { id = 11417, level = 40, tab = 1, cost = 13500, faction = "Horde" }, -- Portal: Orgrimmar
        { id = 10059, level = 40, tab = 1, cost = 13500, faction = "Alliance" }, -- Portal: Stormwind
        { id = 11418, level = 40, tab = 1, cost = 13500, faction = "Horde" }, -- Portal: Undercity
        { id = 8458, level = 40, tab = 2, rank = 3, cost = 15000, prev = 8457 }, -- Fire Ward 3
        { id = 8423, level = 40, tab = 2, rank = 4, cost = 15000, prev = 8422 }, -- Flamestrike 4
        { id = 401502, level = 40, tab = 2, rank = 1 }, -- Frostfire Bolt 1
        { id = 8446, level = 40, tab = 2, rank = 4, cost = 15000, prev = 8445 }, -- Scorch 4
        { id = 6131, level = 40, tab = 3, rank = 3, cost = 15000, prev = 865 }, -- Frost Nova 3
        { id = 7320, level = 40, tab = 3, rank = 2, cost = 15000, prev = 7302 }, -- Ice Armor 2
        { id = 10169, level = 42, tab = 1, rank = 3, cost = 18000, prev = 8455 }, -- Amplify Magic 3
        { id = 10156, level = 42, tab = 1, rank = 4, cost = 22750, prev = 1461 }, -- Arcane Intellect 4
        { id = 10144, level = 42, tab = 1, rank = 5, cost = 22750, prev = 6129 }, -- Conjure Food 5
        { id = 10148, level = 42, tab = 2, rank = 8, cost = 22750, prev = 8402 }, -- Fireball 8
        { id = 12524, level = 42, tab = 2, rank = 5, cost = 900, prev = 12523, requires = 11366 }, -- Pyroblast 5
        { id = 10159, level = 42, tab = 3, rank = 3, cost = 22750, prev = 8492 }, -- Cone of Cold 3
        { id = 8462, level = 42, tab = 3, rank = 3, cost = 18000, prev = 8461 }, -- Frost Ward 3
        { id = 1240045, level = 42, tab = 3, rank = 4, prev = 1240044, requires = 1312002 }, -- Ice Lance 4
        { id = 10191, level = 44, tab = 1, rank = 4, cost = 23000, prev = 8495 }, -- Mana Shield 4
        { id = 13019, level = 44, tab = 2, rank = 3, cost = 1150, prev = 13018, requires = 11113 }, -- Blast Wave 3
        { id = 10185, level = 44, tab = 3, rank = 4, cost = 23000, prev = 8427 }, -- Blizzard 4
        { id = 10179, level = 44, tab = 3, rank = 8, cost = 23000, prev = 8408 }, -- Frostbolt 8
        { id = 10201, level = 46, tab = 1, rank = 5, cost = 26000, prev = 8439 }, -- Arcane Explosion 5
        { id = 22782, level = 46, tab = 1, rank = 2, cost = 28000, prev = 6117 }, -- Mage Armor 2
        { id = 10197, level = 46, tab = 2, rank = 6, cost = 26000, prev = 8413 }, -- Fire Blast 6
        { id = 10205, level = 46, tab = 2, rank = 5, cost = 26000, prev = 8446 }, -- Scorch 5
        { id = 13031, level = 46, tab = 3, rank = 2, cost = 6500, prev = 11426, requires = 11426 }, -- Ice Barrier 2
        { id = 10211, level = 48, tab = 1, rank = 6, cost = 28000, prev = 8417 }, -- Arcane Missiles 6
        { id = 10053, level = 48, tab = 1, cost = 28000, needs = { 3552 } }, -- Conjure Mana Citrine
        { id = 10173, level = 48, tab = 1, rank = 4, cost = 28000, prev = 8451 }, -- Dampen Magic 4
        { id = 10149, level = 48, tab = 2, rank = 9, cost = 28000, prev = 10148 }, -- Fireball 9
        { id = 10215, level = 48, tab = 2, rank = 5, cost = 28000, prev = 8423 }, -- Flamestrike 5
        { id = 12525, level = 48, tab = 2, rank = 6, cost = 900, prev = 12524, requires = 11366 }, -- Pyroblast 6
        { id = 1240046, level = 48, tab = 3, rank = 5, prev = 1240045, requires = 1312002 }, -- Ice Lance 5
        { id = 1239699, level = 50, tab = 1, rank = 4, prev = 1239697, requires = 400574 }, -- Arcane Blast 4
        { id = 10139, level = 50, tab = 1, rank = 6, cost = 32000, prev = 10138 }, -- Conjure Water 6
        { id = 11419, level = 50, tab = 1, cost = 28800, faction = "Alliance" }, -- Portal: Darnassus
        { id = 11420, level = 50, tab = 1, cost = 28800, faction = "Horde" }, -- Portal: Thunder Bluff
        { id = 1297659, level = 50, tab = 1 }, -- Teleport: Dalaran
        { id = 10223, level = 50, tab = 2, rank = 4, cost = 32000, prev = 8458 }, -- Fire Ward 4
        { id = 1237312, level = 50, tab = 2, rank = 2, prev = 401502 }, -- Frostfire Bolt 2
        { id = 10160, level = 50, tab = 3, rank = 4, cost = 32000, prev = 10159 }, -- Cone of Cold 4
        { id = 10180, level = 50, tab = 3, rank = 9, cost = 32000, prev = 10179 }, -- Frostbolt 9
        { id = 10219, level = 50, tab = 3, rank = 3, cost = 32000, prev = 7320 }, -- Ice Armor 3
        { id = 10145, level = 52, tab = 1, rank = 6, cost = 35000, prev = 10144 }, -- Conjure Food 6
        { id = 10192, level = 52, tab = 1, rank = 5, cost = 35000, prev = 10191 }, -- Mana Shield 5
        { id = 13020, level = 52, tab = 2, rank = 4, cost = 1750, prev = 13019, requires = 11113 }, -- Blast Wave 4
        { id = 10206, level = 52, tab = 2, rank = 6, cost = 35000, prev = 10205 }, -- Scorch 6
        { id = 10186, level = 52, tab = 3, rank = 5, cost = 35000, prev = 10185 }, -- Blizzard 5
        { id = 10177, level = 52, tab = 3, rank = 4, cost = 35000, prev = 8462 }, -- Frost Ward 4
        { id = 13032, level = 52, tab = 3, rank = 3, cost = 8750, prev = 13031, requires = 11426 }, -- Ice Barrier 3
        { id = 10170, level = 54, tab = 1, rank = 4, cost = 36000, prev = 10169 }, -- Amplify Magic 4
        { id = 10202, level = 54, tab = 1, rank = 6, cost = 36000, prev = 10201 }, -- Arcane Explosion 6
        { id = 10199, level = 54, tab = 2, rank = 7, cost = 36000, prev = 10197 }, -- Fire Blast 7
        { id = 10150, level = 54, tab = 2, rank = 10, cost = 36000, prev = 10149 }, -- Fireball 10
        { id = 12526, level = 54, tab = 2, rank = 7, cost = 1800, prev = 12525, requires = 11366 }, -- Pyroblast 7
        { id = 10230, level = 54, tab = 3, rank = 4, cost = 36000, prev = 6131 }, -- Frost Nova 4
        { id = 23028, level = 56, tab = 1, rank = 1, book = 18600 }, -- Arcane Brilliance 1
        { id = 10157, level = 56, tab = 1, rank = 5, cost = 38000, prev = 10156 }, -- Arcane Intellect 5
        { id = 10212, level = 56, tab = 1, rank = 7, cost = 38000, prev = 10211 }, -- Arcane Missiles 7
        { id = 25345, level = 56, tab = 1, rank = 8, book = 21280, prev = 10212 }, -- Arcane Missiles 8
        { id = 10216, level = 56, tab = 2, rank = 6, cost = 38000, prev = 10215 }, -- Flamestrike 6
        { id = 10181, level = 56, tab = 3, rank = 10, cost = 38000, prev = 10180 }, -- Frostbolt 10
        { id = 1240047, level = 56, tab = 3, rank = 6, prev = 1240046, requires = 1312002 }, -- Ice Lance 6
        { id = 10054, level = 58, tab = 1, cost = 40000, needs = { 10053 } }, -- Conjure Mana Ruby
        { id = 22783, level = 58, tab = 1, rank = 3, cost = 40000, prev = 22782 }, -- Mage Armor 3
        { id = 10207, level = 58, tab = 2, rank = 7, cost = 40000, prev = 10206 }, -- Scorch 7
        { id = 10161, level = 58, tab = 3, rank = 5, cost = 40000, prev = 10160 }, -- Cone of Cold 5
        { id = 13033, level = 58, tab = 3, rank = 4, cost = 9000, prev = 13032, requires = 11426 }, -- Ice Barrier 4
        { id = 1239700, level = 60, tab = 1, rank = 5, prev = 1239699, requires = 400574 }, -- Arcane Blast 5
        { id = 28612, level = 60, tab = 1, rank = 7, book = 22897, prev = 10145 }, -- Conjure Food 7
        { id = 10140, level = 60, tab = 1, rank = 7, prev = 10139 }, -- Conjure Water 7
        { id = 468766, level = 60, tab = 1, rank = 8, prev = 10140 }, -- Conjure Water 8
        { id = 10174, level = 60, tab = 1, rank = 5, cost = 42000, prev = 10173 }, -- Dampen Magic 5
        { id = 10193, level = 60, tab = 1, rank = 6, cost = 42000, prev = 10192 }, -- Mana Shield 6
        { id = 12826, level = 60, tab = 1, rank = 4, cost = 42000, prev = 12825 }, -- Polymorph 4
        { id = 28270, level = 60, tab = 1, book = 4144 }, -- Polymorph: Cow
        { id = 13021, level = 60, tab = 2, rank = 5, cost = 2100, prev = 13020, requires = 11113 }, -- Blast Wave 5
        { id = 10225, level = 60, tab = 2, rank = 5, cost = 42000, prev = 10223 }, -- Fire Ward 5
        { id = 10151, level = 60, tab = 2, rank = 11, cost = 42000, prev = 10150 }, -- Fireball 11
        { id = 25306, level = 60, tab = 2, rank = 12, book = 21279, prev = 10151 }, -- Fireball 12
        { id = 1237313, level = 60, tab = 2, rank = 3, prev = 1237312 }, -- Frostfire Bolt 3
        { id = 18809, level = 60, tab = 2, rank = 8, cost = 1890, prev = 12526, requires = 11366 }, -- Pyroblast 8
        { id = 10187, level = 60, tab = 3, rank = 6, cost = 42000, prev = 10186 }, -- Blizzard 6
        { id = 28609, level = 60, tab = 3, rank = 5, book = 22890, prev = 10177 }, -- Frost Ward 5
        { id = 25304, level = 60, tab = 3, rank = 11, book = 21214, prev = 10181 }, -- Frostbolt 11
        { id = 10220, level = 60, tab = 3, rank = 4, cost = 42000, prev = 10219 }, -- Ice Armor 4
    },
}
