-- Generated by tools/build_data.py. Do not edit by hand.
-- Forever client build 1.60.1.69876.
local _, SBE = ...

SBE.Data.PALADIN = {
    tabs = { "Holy", "Protection", "Retribution", "General" },
    spells = {
        { id = 465, level = 1, tab = 2, rank = 1, cost = 10 }, -- Devotion Aura 1
        { id = 19740, level = 4, tab = 3, rank = 1, cost = 100 }, -- Blessing of Might 1
        { id = 20271, level = 4, tab = 3, cost = 100 }, -- Judgement
        { id = 639, level = 6, tab = 1, rank = 2, cost = 100, prev = 635 }, -- Holy Light 2
        { id = 498, level = 6, tab = 2, rank = 1, cost = 100 }, -- Divine Protection 1
        { id = 679, level = 6, tab = 3, rank = 1 }, -- Holy Strike 1
        { id = 21082, level = 6, tab = 3, rank = 1, cost = 100 }, -- Seal of the Crusader 1
        { id = 3127, level = 8, tab = 4, cost = 100, general = true }, -- Parry
        { id = 1152, level = 8, tab = 1, cost = 100 }, -- Purify
        { id = 853, level = 8, tab = 2, rank = 1, cost = 100 }, -- Hammer of Justice 1
        { id = 633, level = 10, tab = 1, rank = 1, cost = 300 }, -- Lay on Hands 1
        { id = 20287, level = 10, tab = 1, rank = 2, cost = 300, prev = 20154 }, -- Seal of Righteousness 2
        { id = 1022, level = 10, tab = 2, rank = 1, cost = 300 }, -- Blessing of Protection 1
        { id = 10290, level = 10, tab = 2, rank = 2, cost = 300, prev = 465 }, -- Devotion Aura 2
        { id = 1311649, level = 10, tab = 2, rank = 1 }, -- Seal of Fury 1
        { id = 7328, level = 12, tab = 1, rank = 1, quest = true }, -- Redemption 1
        { id = 19834, level = 12, tab = 3, rank = 2, cost = 1000, prev = 19740 }, -- Blessing of Might 2
        { id = 678, level = 12, tab = 3, rank = 2, prev = 679 }, -- Holy Strike 2
        { id = 20162, level = 12, tab = 3, rank = 2, cost = 1000, prev = 21082 }, -- Seal of the Crusader 2
        { id = 19742, level = 14, tab = 1, rank = 1, cost = 2000 }, -- Blessing of Wisdom 1
        { id = 647, level = 14, tab = 1, rank = 3, cost = 2000, prev = 639 }, -- Holy Light 3
        { id = 25780, level = 16, tab = 2, cost = 3000 }, -- Righteous Fury
        { id = 7294, level = 16, tab = 3, rank = 1, cost = 3000 }, -- Retribution Aura 1
        { id = 20288, level = 18, tab = 1, rank = 3, cost = 3500, prev = 20287 }, -- Seal of Righteousness 3
        { id = 1044, level = 18, tab = 2, cost = 3500 }, -- Blessing of Freedom
        { id = 5573, level = 18, tab = 2, rank = 2, cost = 3500, prev = 498 }, -- Divine Protection 2
        { id = 1311656, level = 18, tab = 2, rank = 2, prev = 1311649 }, -- Seal of Fury 2
        { id = 26573, level = 20, tab = 1, rank = 1 }, -- Consecration 1
        { id = 879, level = 20, tab = 1, rank = 1, cost = 4000 }, -- Exorcism 1
        { id = 19750, level = 20, tab = 1, rank = 1, cost = 4000 }, -- Flash of Light 1
        { id = 5502, level = 20, tab = 1 }, -- Sense Undead
        { id = 20217, level = 20, tab = 2 }, -- Blessing of Kings
        { id = 643, level = 20, tab = 2, rank = 3, cost = 4000, prev = 10290 }, -- Devotion Aura 3
        { id = 1866, level = 20, tab = 3, rank = 3, prev = 678 }, -- Holy Strike 3
        { id = 1026, level = 22, tab = 1, rank = 4, cost = 4000, prev = 647 }, -- Holy Light 4
        { id = 19746, level = 22, tab = 2, cost = 4000 }, -- Concentration Aura
        { id = 20164, level = 22, tab = 2, cost = 4000 }, -- Seal of Justice
        { id = 19835, level = 22, tab = 3, rank = 3, cost = 4000, prev = 19834 }, -- Blessing of Might 3
        { id = 20305, level = 22, tab = 3, rank = 3, cost = 4000, prev = 20162 }, -- Seal of the Crusader 3
        { id = 19850, level = 24, tab = 1, rank = 2, cost = 5000, prev = 19742 }, -- Blessing of Wisdom 2
        { id = 10322, level = 24, tab = 1, rank = 2, cost = 5000, prev = 7328 }, -- Redemption 2
        { id = 2878, level = 24, tab = 1, rank = 1, cost = 5000 }, -- Turn Undead 1
        { id = 5599, level = 24, tab = 2, rank = 2, cost = 5000, prev = 1022 }, -- Blessing of Protection 2
        { id = 5588, level = 24, tab = 2, rank = 2, cost = 5000, prev = 853 }, -- Hammer of Justice 2
        { id = 20183, level = 25, tab = 2, rank = 3 }, -- Judgement of Fury 3
        { id = 20163, level = 25, tab = 2, rank = 3, prev = 1311656 }, -- Seal of Fury 3
        { id = 19939, level = 26, tab = 1, rank = 2, cost = 6000, prev = 19750 }, -- Flash of Light 2
        { id = 20289, level = 26, tab = 1, rank = 4, cost = 6000, prev = 20288 }, -- Seal of Righteousness 4
        { id = 1038, level = 26, tab = 2, cost = 6000 }, -- Blessing of Salvation
        { id = 10298, level = 26, tab = 3, rank = 2, cost = 6000, prev = 7294 }, -- Retribution Aura 2
        { id = 5614, level = 28, tab = 1, rank = 2, cost = 9000, prev = 879 }, -- Exorcism 2
        { id = 19876, level = 28, tab = 2, rank = 1, cost = 9000 }, -- Shadow Resistance Aura 1
        { id = 680, level = 28, tab = 3, rank = 4, prev = 1866 }, -- Holy Strike 4
        { id = 20116, level = 30, tab = 1, rank = 2, prev = 26573 }, -- Consecration 2
        { id = 1042, level = 30, tab = 1, rank = 5, cost = 11000, prev = 1026 }, -- Holy Light 5
        { id = 2800, level = 30, tab = 1, rank = 2, cost = 11000, prev = 633 }, -- Lay on Hands 2
        { id = 20165, level = 30, tab = 1, rank = 1, cost = 11000 }, -- Seal of Light 1
        { id = 10291, level = 30, tab = 2, rank = 4, cost = 11000, prev = 643 }, -- Devotion Aura 4
        { id = 19752, level = 30, tab = 2, cost = 11000 }, -- Divine Intervention
        { id = 20915, level = 30, tab = 3, rank = 2, cost = 200, prev = 20375, requires = 20375 }, -- Seal of Command 2
        { id = 19888, level = 32, tab = 2, rank = 1, cost = 12000 }, -- Frost Resistance Aura 1
        { id = 19836, level = 32, tab = 3, rank = 4, cost = 12000, prev = 19835 }, -- Blessing of Might 4
        { id = 20306, level = 32, tab = 3, rank = 4, cost = 12000, prev = 20305 }, -- Seal of the Crusader 4
        { id = 19852, level = 34, tab = 1, rank = 3, cost = 13000, prev = 19850 }, -- Blessing of Wisdom 3
        { id = 19940, level = 34, tab = 1, rank = 3, cost = 13000, prev = 19939 }, -- Flash of Light 3
        { id = 20290, level = 34, tab = 1, rank = 5, cost = 13000, prev = 20289 }, -- Seal of Righteousness 5
        { id = 642, level = 34, tab = 2, rank = 1, cost = 13000 }, -- Divine Shield 1
        { id = 20411, level = 34, tab = 2, rank = 4, prev = 20183 }, -- Judgement of Fury 4
        { id = 20419, level = 34, tab = 2, rank = 4, prev = 20163 }, -- Seal of Fury 4
        { id = 5615, level = 36, tab = 1, rank = 3, cost = 14000, prev = 5614 }, -- Exorcism 3
        { id = 10324, level = 36, tab = 1, rank = 3, cost = 14000, prev = 10322 }, -- Redemption 3
        { id = 19891, level = 36, tab = 2, rank = 1, cost = 14000 }, -- Fire Resistance Aura 1
        { id = 2495, level = 36, tab = 3, rank = 5, prev = 680 }, -- Holy Strike 5
        { id = 10299, level = 36, tab = 3, rank = 3, cost = 14000, prev = 10298 }, -- Retribution Aura 3
        { id = 3472, level = 38, tab = 1, rank = 6, cost = 16000, prev = 1042 }, -- Holy Light 6
        { id = 20166, level = 38, tab = 1, rank = 1, cost = 16000 }, -- Seal of Wisdom 1
        { id = 5627, level = 38, tab = 1, rank = 2, cost = 16000, prev = 2878 }, -- Turn Undead 2
        { id = 10278, level = 38, tab = 2, rank = 3, cost = 16000, prev = 5599 }, -- Blessing of Protection 3
        { id = 750, level = 40, tab = 4, cost = 20000, general = true }, -- Plate Mail
        { id = 19977, level = 40, tab = 1, rank = 1, cost = 20000 }, -- Blessing of Light 1
        { id = 20922, level = 40, tab = 1, rank = 3, prev = 20116 }, -- Consecration 3
        { id = 20473, level = 40, tab = 1, rank = 2, prev = 1311606, requires = 1311606 }, -- Holy Shock 2
        { id = 20347, level = 40, tab = 1, rank = 2, cost = 20000, prev = 20165 }, -- Seal of Light 2
        { id = 1032, level = 40, tab = 2, rank = 5, cost = 20000, prev = 10291 }, -- Devotion Aura 5
        { id = 5589, level = 40, tab = 2, rank = 3, cost = 20000, prev = 5588 }, -- Hammer of Justice 3
        { id = 19895, level = 40, tab = 2, rank = 2, cost = 20000, prev = 19876 }, -- Shadow Resistance Aura 2
        { id = 20918, level = 40, tab = 3, rank = 3, cost = 1000, prev = 20915, requires = 20375 }, -- Seal of Command 3
        { id = 4987, level = 42, tab = 1, cost = 21000 }, -- Cleanse
        { id = 19941, level = 42, tab = 1, rank = 4, cost = 21000, prev = 19940 }, -- Flash of Light 4
        { id = 20291, level = 42, tab = 1, rank = 6, cost = 21000, prev = 20290 }, -- Seal of Righteousness 6
        { id = 20412, level = 42, tab = 2, rank = 5, prev = 20411 }, -- Judgement of Fury 5
        { id = 20421, level = 42, tab = 2, rank = 5, prev = 20419 }, -- Seal of Fury 5
        { id = 19837, level = 42, tab = 3, rank = 5, cost = 21000, prev = 19836 }, -- Blessing of Might 5
        { id = 20307, level = 42, tab = 3, rank = 5, cost = 21000, prev = 20306 }, -- Seal of the Crusader 5
        { id = 19853, level = 44, tab = 1, rank = 4, cost = 22000, prev = 19852 }, -- Blessing of Wisdom 4
        { id = 10312, level = 44, tab = 1, rank = 4, cost = 22000, prev = 5615 }, -- Exorcism 4
        { id = 24275, level = 44, tab = 1, rank = 1, cost = 22000 }, -- Hammer of Wrath 1
        { id = 19897, level = 44, tab = 2, rank = 2, cost = 22000, prev = 19888 }, -- Frost Resistance Aura 2
        { id = 5569, level = 44, tab = 3, rank = 6, prev = 2495 }, -- Holy Strike 6
        { id = 10328, level = 46, tab = 1, rank = 7, cost = 24000, prev = 3472 }, -- Holy Light 7
        { id = 6940, level = 46, tab = 2, rank = 1, cost = 24000 }, -- Blessing of Sacrifice 1
        { id = 10300, level = 46, tab = 3, rank = 4, cost = 24000, prev = 10299 }, -- Retribution Aura 4
        { id = 20929, level = 48, tab = 1, rank = 3, cost = 1170, prev = 20473, requires = 1311606 }, -- Holy Shock 3
        { id = 20772, level = 48, tab = 1, rank = 4, cost = 26000, prev = 10324 }, -- Redemption 4
        { id = 20356, level = 48, tab = 1, rank = 2, cost = 26000, prev = 20166 }, -- Seal of Wisdom 2
        { id = 19899, level = 48, tab = 2, rank = 2, cost = 26000, prev = 19891 }, -- Fire Resistance Aura 2
        { id = 19978, level = 50, tab = 1, rank = 2, cost = 28000, prev = 19977 }, -- Blessing of Light 2
        { id = 20923, level = 50, tab = 1, rank = 4, prev = 20922 }, -- Consecration 4
        { id = 19942, level = 50, tab = 1, rank = 5, cost = 28000, prev = 19941 }, -- Flash of Light 5
        { id = 2812, level = 50, tab = 1, rank = 1, cost = 28000 }, -- Holy Wrath 1
        { id = 10310, level = 50, tab = 1, rank = 3, cost = 28000, prev = 2800 }, -- Lay on Hands 3
        { id = 1311590, level = 50, tab = 1, rank = 2, prev = 1310911, requires = 1310911 }, -- Light's Vigil 2
        { id = 20348, level = 50, tab = 1, rank = 3, cost = 28000, prev = 20347 }, -- Seal of Light 3
        { id = 20292, level = 50, tab = 1, rank = 7, cost = 28000, prev = 20291 }, -- Seal of Righteousness 7
        { id = 10292, level = 50, tab = 2, rank = 6, cost = 28000, prev = 1032 }, -- Devotion Aura 6
        { id = 1020, level = 50, tab = 2, rank = 2, cost = 28000, prev = 642 }, -- Divine Shield 2
        { id = 20927, level = 50, tab = 2, rank = 2, cost = 1260, prev = 20925, requires = 20925 }, -- Holy Shield 2
        { id = 20413, level = 50, tab = 2, rank = 6, prev = 20412 }, -- Judgement of Fury 6
        { id = 20422, level = 50, tab = 2, rank = 6, prev = 20421 }, -- Seal of Fury 6
        { id = 20919, level = 50, tab = 3, rank = 4, cost = 1260, prev = 20918, requires = 20375 }, -- Seal of Command 4
        { id = 10313, level = 52, tab = 1, rank = 5, cost = 34000, prev = 10312 }, -- Exorcism 5
        { id = 24274, level = 52, tab = 1, rank = 2, cost = 34000, prev = 24275 }, -- Hammer of Wrath 2
        { id = 10326, level = 52, tab = 1, rank = 3, cost = 34000, prev = 5627 }, -- Turn Undead 3
        { id = 19896, level = 52, tab = 2, rank = 3, cost = 34000, prev = 19895 }, -- Shadow Resistance Aura 3
        { id = 19838, level = 52, tab = 3, rank = 6, cost = 34000, prev = 19837 }, -- Blessing of Might 6
        { id = 25782, level = 52, tab = 3, rank = 1, cost = 46000, needs = { 19838 } }, -- Greater Blessing of Might 1
        { id = 10332, level = 52, tab = 3, rank = 7, prev = 5569 }, -- Holy Strike 7
        { id = 20308, level = 52, tab = 3, rank = 6, cost = 34000, prev = 20307 }, -- Seal of the Crusader 6
        { id = 19854, level = 54, tab = 1, rank = 5, cost = 40000, prev = 19853 }, -- Blessing of Wisdom 5
        { id = 25894, level = 54, tab = 1, rank = 1, cost = 40000, needs = { 19854 } }, -- Greater Blessing of Wisdom 1
        { id = 10329, level = 54, tab = 1, rank = 8, cost = 40000, prev = 10328 }, -- Holy Light 8
        { id = 20729, level = 54, tab = 2, rank = 2, cost = 40000, prev = 6940 }, -- Blessing of Sacrifice 2
        { id = 10308, level = 54, tab = 2, rank = 4, cost = 40000, prev = 5589 }, -- Hammer of Justice 4
        { id = 20930, level = 56, tab = 1, rank = 4, cost = 2100, prev = 20929, requires = 1311606 }, -- Holy Shock 4
        { id = 19898, level = 56, tab = 2, rank = 3, cost = 42000, prev = 19897 }, -- Frost Resistance Aura 3
        { id = 10301, level = 56, tab = 3, rank = 5, cost = 42000, prev = 10300 }, -- Retribution Aura 5
        { id = 19943, level = 58, tab = 1, rank = 6, cost = 44000, prev = 19942 }, -- Flash of Light 6
        { id = 20293, level = 58, tab = 1, rank = 8, cost = 44000, prev = 20292 }, -- Seal of Righteousness 8
        { id = 20357, level = 58, tab = 1, rank = 3, cost = 44000, prev = 20356 }, -- Seal of Wisdom 3
        { id = 20414, level = 58, tab = 2, rank = 7, prev = 20413 }, -- Judgement of Fury 7
        { id = 20423, level = 58, tab = 2, rank = 7, prev = 20422 }, -- Seal of Fury 7
        { id = 19979, level = 60, tab = 1, rank = 3, cost = 46000, prev = 19978 }, -- Blessing of Light 3
        { id = 25290, level = 60, tab = 1, rank = 6, book = 21288, prev = 19854 }, -- Blessing of Wisdom 6
        { id = 20924, level = 60, tab = 1, rank = 5, prev = 20923 }, -- Consecration 5
        { id = 10314, level = 60, tab = 1, rank = 6, cost = 46000, prev = 10313 }, -- Exorcism 6
        { id = 25890, level = 60, tab = 1, rank = 1, cost = 46000, needs = { 19979 } }, -- Greater Blessing of Light 1
        { id = 25918, level = 60, tab = 1, rank = 2, cost = 46000, prev = 25894, needs = { 25290 } }, -- Greater Blessing of Wisdom 2
        { id = 24239, level = 60, tab = 1, rank = 3, cost = 46000, prev = 24274 }, -- Hammer of Wrath 3
        { id = 25292, level = 60, tab = 1, rank = 9, book = 21290, prev = 10329 }, -- Holy Light 9
        { id = 10318, level = 60, tab = 1, rank = 2, cost = 46000, prev = 2812 }, -- Holy Wrath 2
        { id = 1311595, level = 60, tab = 1, rank = 3, prev = 1311590, requires = 1310911 }, -- Light's Vigil 3
        { id = 20773, level = 60, tab = 1, rank = 5, cost = 46000, prev = 20772 }, -- Redemption 5
        { id = 20349, level = 60, tab = 1, rank = 4, cost = 46000, prev = 20348 }, -- Seal of Light 4
        { id = 10293, level = 60, tab = 2, rank = 7, cost = 46000, prev = 10292 }, -- Devotion Aura 7
        { id = 19900, level = 60, tab = 2, rank = 3, cost = 46000, prev = 19899 }, -- Fire Resistance Aura 3
        { id = 25898, level = 60, tab = 2 }, -- Greater Blessing of Kings
        { id = 25895, level = 60, tab = 2, cost = 46000, needs = { 1038 } }, -- Greater Blessing of Salvation
        { id = 20928, level = 60, tab = 2, rank = 3, cost = 2070, prev = 20927, requires = 20925 }, -- Holy Shield 3
        { id = 25291, level = 60, tab = 3, rank = 7, book = 21289, prev = 19838 }, -- Blessing of Might 7
        { id = 25916, level = 60, tab = 3, rank = 2, cost = 41400, prev = 25782, needs = { 25291 } }, -- Greater Blessing of Might 2
        { id = 10333, level = 60, tab = 3, rank = 8, prev = 10332 }, -- Holy Strike 8
        { id = 20920, level = 60, tab = 3, rank = 5, cost = 2070, prev = 20919, requires = 20375 }, -- Seal of Command 5
    },
}
