-- Generated by tools/build_data.py. Do not edit by hand.
-- Forever client build 1.60.1.69876.
local _, SBE = ...

SBE.Data.PRIEST = {
    tabs = { "Discipline", "Holy", "Shadow Magic" },
    spells = {
        { id = 1243, level = 1, tab = 1, rank = 1, cost = 10 }, -- Power Word: Fortitude 1
        { id = 2052, level = 4, tab = 2, rank = 2, cost = 100, prev = 2050 }, -- Lesser Heal 2
        { id = 589, level = 4, tab = 3, rank = 1, cost = 100 }, -- Shadow Word: Pain 1
        { id = 17, level = 6, tab = 1, rank = 1, cost = 100 }, -- Power Word: Shield 1
        { id = 591, level = 6, tab = 2, rank = 2, cost = 100, prev = 585 }, -- Smite 2
        { id = 139, level = 8, tab = 2, rank = 1, cost = 200 }, -- Renew 1
        { id = 586, level = 8, tab = 3, rank = 1, cost = 200 }, -- Fade 1
        { id = 1277455, level = 10, tab = 1 }, -- Confounding Flash
        { id = 10797, level = 10, tab = 1, rank = 1, race = 4 }, -- Starshards 1
        { id = 13908, level = 10, tab = 2, rank = 1 }, -- Desperate Prayer 1
        { id = 1277370, level = 10, tab = 2, rank = 1 }, -- Divine Grace 1
        { id = 2053, level = 10, tab = 2, rank = 3, cost = 300, prev = 2052 }, -- Lesser Heal 3
        { id = 2006, level = 10, tab = 2, rank = 1, cost = 300 }, -- Resurrection 1
        { id = 9035, level = 10, tab = 3, rank = 1, race = 8 }, -- Hex of Weakness 1
        { id = 8092, level = 10, tab = 3, rank = 1, cost = 300 }, -- Mind Blast 1
        { id = 594, level = 10, tab = 3, rank = 2, cost = 300, prev = 589 }, -- Shadow Word: Pain 2
        { id = 2652, level = 10, tab = 3, rank = 1, race = 5 }, -- Touch of Weakness 1
        { id = 588, level = 12, tab = 1, rank = 1, cost = 800 }, -- Inner Fire 1
        { id = 1244, level = 12, tab = 1, rank = 2, cost = 800, prev = 1243 }, -- Power Word: Fortitude 2
        { id = 592, level = 12, tab = 1, rank = 2, cost = 800, prev = 17 }, -- Power Word: Shield 2
        { id = 528, level = 14, tab = 2, cost = 1200 }, -- Cure Disease
        { id = 6074, level = 14, tab = 2, rank = 2, cost = 1200, prev = 139 }, -- Renew 2
        { id = 598, level = 14, tab = 2, rank = 3, cost = 1200, prev = 591 }, -- Smite 3
        { id = 8122, level = 14, tab = 3, rank = 1, cost = 1200 }, -- Psychic Scream 1
        { id = 2054, level = 16, tab = 2, rank = 1, cost = 1600 }, -- Heal 1
        { id = 8102, level = 16, tab = 3, rank = 2, cost = 1600, prev = 8092 }, -- Mind Blast 2
        { id = 527, level = 18, tab = 1, rank = 1, cost = 2000 }, -- Dispel Magic 1
        { id = 600, level = 18, tab = 1, rank = 3, cost = 2000, prev = 592 }, -- Power Word: Shield 3
        { id = 19296, level = 18, tab = 1, rank = 2, cost = 100, prev = 10797, race = 4 }, -- Starshards 2
        { id = 19236, level = 18, tab = 2, rank = 2, cost = 100, prev = 13908 }, -- Desperate Prayer 2
        { id = 1277371, level = 18, tab = 2, rank = 2, prev = 1277370 }, -- Divine Grace 2
        { id = 970, level = 18, tab = 3, rank = 3, cost = 2000, prev = 594 }, -- Shadow Word: Pain 3
        { id = 1277462, level = 20, tab = 1, rank = 1 }, -- Contingency Plan 1
        { id = 2651, level = 20, tab = 1, race = 4 }, -- Elune's Grace
        { id = 13896, level = 20, tab = 1, rank = 1, race = 1 }, -- Feedback 1
        { id = 7128, level = 20, tab = 1, rank = 2, cost = 3000, prev = 588 }, -- Inner Fire 2
        { id = 9484, level = 20, tab = 1, rank = 1, cost = 3000 }, -- Shackle Undead 1
        { id = 1277331, level = 20, tab = 2, rank = 1 }, -- Chastise 1
        { id = 6346, level = 20, tab = 2 }, -- Fear Ward
        { id = 2061, level = 20, tab = 2, rank = 1, cost = 3000 }, -- Flash Heal 1
        { id = 14914, level = 20, tab = 2, rank = 1, cost = 3000 }, -- Holy Fire 1
        { id = 6075, level = 20, tab = 2, rank = 3, cost = 3000, prev = 6074 }, -- Renew 3
        { id = 1277324, level = 20, tab = 3, rank = 1 }, -- Dark Sacrifice 1
        { id = 2944, level = 20, tab = 3, rank = 1 }, -- Devouring Plague 1
        { id = 9578, level = 20, tab = 3, rank = 2, cost = 3000, prev = 586 }, -- Fade 2
        { id = 19281, level = 20, tab = 3, rank = 2, cost = 150, prev = 9035, race = 8 }, -- Hex of Weakness 2
        { id = 453, level = 20, tab = 3, rank = 1, cost = 3000 }, -- Mind Soothe 1
        { id = 18137, level = 20, tab = 3, rank = 1, race = 8 }, -- Shadowguard 1
        { id = 19261, level = 20, tab = 3, rank = 2, cost = 200, prev = 2652, race = 5 }, -- Touch of Weakness 2
        { id = 2055, level = 22, tab = 2, rank = 2, cost = 4000, prev = 2054 }, -- Heal 2
        { id = 2010, level = 22, tab = 2, rank = 2, cost = 4000, prev = 2006 }, -- Resurrection 2
        { id = 984, level = 22, tab = 2, rank = 4, cost = 4000, prev = 598 }, -- Smite 4
        { id = 8103, level = 22, tab = 3, rank = 3, cost = 4000, prev = 8102 }, -- Mind Blast 3
        { id = 2096, level = 22, tab = 3, rank = 1, cost = 4000 }, -- Mind Vision 1
        { id = 8129, level = 24, tab = 1, rank = 1, cost = 5000 }, -- Mana Burn 1
        { id = 1245, level = 24, tab = 1, rank = 3, cost = 5000, prev = 1244 }, -- Power Word: Fortitude 3
        { id = 3747, level = 24, tab = 1, rank = 4, cost = 5000, prev = 600 }, -- Power Word: Shield 4
        { id = 15262, level = 24, tab = 2, rank = 2, cost = 5000, prev = 14914 }, -- Holy Fire 2
        { id = 19299, level = 26, tab = 1, rank = 3, cost = 300, prev = 19296, race = 4 }, -- Starshards 3
        { id = 19238, level = 26, tab = 2, rank = 3, cost = 300, prev = 19236 }, -- Desperate Prayer 3
        { id = 1277372, level = 26, tab = 2, rank = 3, prev = 1277371 }, -- Divine Grace 3
        { id = 9472, level = 26, tab = 2, rank = 2, cost = 6000, prev = 2061 }, -- Flash Heal 2
        { id = 6076, level = 26, tab = 2, rank = 4, cost = 6000, prev = 6075 }, -- Renew 4
        { id = 992, level = 26, tab = 3, rank = 4, cost = 6000, prev = 970 }, -- Shadow Word: Pain 4
        { id = 6063, level = 28, tab = 2, rank = 3, cost = 8000, prev = 2055 }, -- Heal 3
        { id = 15430, level = 28, tab = 2, rank = 2, cost = 400, prev = 15237, requires = 15237 }, -- Holy Nova 2
        { id = 19276, level = 28, tab = 3, rank = 2, cost = 400, prev = 2944 }, -- Devouring Plague 2
        { id = 8104, level = 28, tab = 3, rank = 4, cost = 8000, prev = 8103 }, -- Mind Blast 4
        { id = 17311, level = 28, tab = 3, rank = 2, cost = 400, prev = 15407, requires = 15407 }, -- Mind Flay 2
        { id = 8124, level = 28, tab = 3, rank = 2, cost = 8000, prev = 8122 }, -- Psychic Scream 2
        { id = 19308, level = 28, tab = 3, rank = 2, cost = 400, prev = 18137, race = 8 }, -- Shadowguard 2
        { id = 1277634, level = 30, tab = 1, rank = 2, prev = 1277462 }, -- Contingency Plan 2
        { id = 14752, level = 30, tab = 1, rank = 1 }, -- Divine Spirit 1
        { id = 19271, level = 30, tab = 1, rank = 2, cost = 450, prev = 13896, race = 1 }, -- Feedback 2
        { id = 602, level = 30, tab = 1, rank = 3, cost = 10000, prev = 7128 }, -- Inner Fire 3
        { id = 6065, level = 30, tab = 1, rank = 5, cost = 10000, prev = 3747 }, -- Power Word: Shield 5
        { id = 1277332, level = 30, tab = 2, rank = 2, prev = 1277331 }, -- Chastise 2
        { id = 15263, level = 30, tab = 2, rank = 3, cost = 10000, prev = 15262 }, -- Holy Fire 3
        { id = 596, level = 30, tab = 2, rank = 1, cost = 10000 }, -- Prayer of Healing 1
        { id = 1004, level = 30, tab = 2, rank = 5, cost = 10000, prev = 984 }, -- Smite 5
        { id = 1277325, level = 30, tab = 3, rank = 2, prev = 1277324 }, -- Dark Sacrifice 2
        { id = 9579, level = 30, tab = 3, rank = 3, cost = 10000, prev = 9578 }, -- Fade 3
        { id = 19282, level = 30, tab = 3, rank = 3, cost = 500, prev = 19281, race = 8 }, -- Hex of Weakness 3
        { id = 605, level = 30, tab = 3, rank = 1, cost = 10000 }, -- Mind Control 1
        { id = 976, level = 30, tab = 3, rank = 1, cost = 10000 }, -- Shadow Protection 1
        { id = 19262, level = 30, tab = 3, rank = 3, cost = 500, prev = 19261, race = 5 }, -- Touch of Weakness 3
        { id = 8131, level = 32, tab = 1, rank = 2, cost = 11000, prev = 8129 }, -- Mana Burn 2
        { id = 552, level = 32, tab = 2, cost = 11000 }, -- Abolish Disease
        { id = 1240770, level = 32, tab = 2, rank = 2, prev = 401937, requires = 401937 }, -- Binding Heal 2
        { id = 9473, level = 32, tab = 2, rank = 3, cost = 11000, prev = 9472 }, -- Flash Heal 3
        { id = 6077, level = 32, tab = 2, rank = 5, cost = 11000, prev = 6076 }, -- Renew 5
        { id = 1309595, level = 32, tab = 3, rank = 1 }, -- Shadow Word: Death 1
        { id = 1706, level = 34, tab = 1, cost = 12000 }, -- Levitate
        { id = 19302, level = 34, tab = 1, rank = 4, cost = 600, prev = 19299, race = 4 }, -- Starshards 4
        { id = 19240, level = 34, tab = 2, rank = 4, cost = 600, prev = 19238 }, -- Desperate Prayer 4
        { id = 1277374, level = 34, tab = 2, rank = 4, prev = 1277372 }, -- Divine Grace 4
        { id = 6064, level = 34, tab = 2, rank = 4, cost = 12000, prev = 6063 }, -- Heal 4
        { id = 10880, level = 34, tab = 2, rank = 3, cost = 12000, prev = 2010 }, -- Resurrection 3
        { id = 8105, level = 34, tab = 3, rank = 5, cost = 12000, prev = 8104 }, -- Mind Blast 5
        { id = 2767, level = 34, tab = 3, rank = 5, cost = 12000, prev = 992 }, -- Shadow Word: Pain 5
        { id = 988, level = 36, tab = 1, rank = 2, cost = 14000, prev = 527 }, -- Dispel Magic 2
        { id = 2791, level = 36, tab = 1, rank = 4, cost = 14000, prev = 1245 }, -- Power Word: Fortitude 4
        { id = 6066, level = 36, tab = 1, rank = 6, cost = 14000, prev = 6065 }, -- Power Word: Shield 6
        { id = 15264, level = 36, tab = 2, rank = 4, cost = 14000, prev = 15263 }, -- Holy Fire 4
        { id = 15431, level = 36, tab = 2, rank = 3, cost = 700, prev = 15430, requires = 15237 }, -- Holy Nova 3
        { id = 19277, level = 36, tab = 3, rank = 3, cost = 700, prev = 19276 }, -- Devouring Plague 3
        { id = 17312, level = 36, tab = 3, rank = 3, cost = 700, prev = 17311, requires = 15407 }, -- Mind Flay 3
        { id = 8192, level = 36, tab = 3, rank = 2, cost = 14000, prev = 453 }, -- Mind Soothe 2
        { id = 19309, level = 36, tab = 3, rank = 3, cost = 700, prev = 19308, race = 8 }, -- Shadowguard 3
        { id = 1240771, level = 38, tab = 2, rank = 3, prev = 1240770, requires = 401937 }, -- Binding Heal 3
        { id = 9474, level = 38, tab = 2, rank = 4, cost = 16000, prev = 9473 }, -- Flash Heal 4
        { id = 6078, level = 38, tab = 2, rank = 6, cost = 16000, prev = 6077 }, -- Renew 6
        { id = 6060, level = 38, tab = 2, rank = 6, cost = 16000, prev = 1004 }, -- Smite 6
        { id = 1277638, level = 40, tab = 1, rank = 3, prev = 1277634 }, -- Contingency Plan 3
        { id = 14818, level = 40, tab = 1, rank = 2, cost = 900, prev = 14752 }, -- Divine Spirit 2
        { id = 19273, level = 40, tab = 1, rank = 3, cost = 810, prev = 19271, race = 1 }, -- Feedback 3
        { id = 1006, level = 40, tab = 1, rank = 4, cost = 18000, prev = 602 }, -- Inner Fire 4
        { id = 10874, level = 40, tab = 1, rank = 3, cost = 18000, prev = 8131 }, -- Mana Burn 3
        { id = 1240720, level = 40, tab = 1, rank = 2, prev = 402174, requires = 402174 }, -- Penance 2
        { id = 9485, level = 40, tab = 1, rank = 2, cost = 18000, prev = 9484 }, -- Shackle Undead 2
        { id = 1277333, level = 40, tab = 2, rank = 3, prev = 1277332 }, -- Chastise 3
        { id = 2060, level = 40, tab = 2, rank = 1, cost = 18000 }, -- Greater Heal 1
        { id = 724, level = 40, tab = 2, rank = 1 }, -- Lightwell 1
        { id = 996, level = 40, tab = 2, rank = 2, cost = 18000, prev = 596 }, -- Prayer of Healing 2
        { id = 1277326, level = 40, tab = 3, rank = 3, prev = 1277325 }, -- Dark Sacrifice 3
        { id = 9592, level = 40, tab = 3, rank = 4, cost = 18000, prev = 9579 }, -- Fade 4
        { id = 19283, level = 40, tab = 3, rank = 4, cost = 900, prev = 19282, race = 8 }, -- Hex of Weakness 4
        { id = 8106, level = 40, tab = 3, rank = 6, cost = 18000, prev = 8105 }, -- Mind Blast 6
        { id = 1309633, level = 40, tab = 3, rank = 2, prev = 1309595 }, -- Shadow Word: Death 2
        { id = 19264, level = 40, tab = 3, rank = 4, cost = 900, prev = 19262, race = 5 }, -- Touch of Weakness 4
        { id = 10898, level = 42, tab = 1, rank = 7, cost = 22000, prev = 6066 }, -- Power Word: Shield 7
        { id = 19303, level = 42, tab = 1, rank = 5, cost = 1100, prev = 19302, race = 4 }, -- Starshards 5
        { id = 19241, level = 42, tab = 2, rank = 5, cost = 1100, prev = 19240 }, -- Desperate Prayer 5
        { id = 1277376, level = 42, tab = 2, rank = 5, prev = 1277374 }, -- Divine Grace 5
        { id = 15265, level = 42, tab = 2, rank = 5, cost = 22000, prev = 15264 }, -- Holy Fire 5
        { id = 10888, level = 42, tab = 3, rank = 3, cost = 22000, prev = 8124 }, -- Psychic Scream 3
        { id = 10957, level = 42, tab = 3, rank = 2, cost = 22000, prev = 976 }, -- Shadow Protection 2
        { id = 10892, level = 42, tab = 3, rank = 6, cost = 22000, prev = 2767 }, -- Shadow Word: Pain 6
        { id = 1240772, level = 44, tab = 2, rank = 4, prev = 1240771, requires = 401937 }, -- Binding Heal 4
        { id = 10915, level = 44, tab = 2, rank = 5, cost = 24000, prev = 9474 }, -- Flash Heal 5
        { id = 27799, level = 44, tab = 2, rank = 4, cost = 1200, prev = 15431, requires = 15237 }, -- Holy Nova 4
        { id = 10927, level = 44, tab = 2, rank = 7, cost = 24000, prev = 6078 }, -- Renew 7
        { id = 19278, level = 44, tab = 3, rank = 4, cost = 1200, prev = 19277 }, -- Devouring Plague 4
        { id = 10911, level = 44, tab = 3, rank = 2, cost = 24000, prev = 605 }, -- Mind Control 2
        { id = 17313, level = 44, tab = 3, rank = 4, cost = 1200, prev = 17312, requires = 15407 }, -- Mind Flay 4
        { id = 10909, level = 44, tab = 3, rank = 2, cost = 24000, prev = 2096 }, -- Mind Vision 2
        { id = 19310, level = 44, tab = 3, rank = 4, cost = 1000, prev = 19309, race = 8 }, -- Shadowguard 4
        { id = 10963, level = 46, tab = 2, rank = 2, cost = 26000, prev = 2060 }, -- Greater Heal 2
        { id = 10881, level = 46, tab = 2, rank = 4, cost = 26000, prev = 10880 }, -- Resurrection 4
        { id = 10933, level = 46, tab = 2, rank = 7, cost = 26000, prev = 6060 }, -- Smite 7
        { id = 10945, level = 46, tab = 3, rank = 7, cost = 26000, prev = 8106 }, -- Mind Blast 7
        { id = 10875, level = 48, tab = 1, rank = 4, cost = 28000, prev = 10874 }, -- Mana Burn 4
        { id = 10937, level = 48, tab = 1, rank = 5, cost = 28000, prev = 2791 }, -- Power Word: Fortitude 5
        { id = 10899, level = 48, tab = 1, rank = 8, cost = 28000, prev = 10898 }, -- Power Word: Shield 8
        { id = 21562, level = 48, tab = 1, rank = 1, book = 17413 }, -- Prayer of Fortitude 1
        { id = 15266, level = 48, tab = 2, rank = 6, cost = 28000, prev = 15265 }, -- Holy Fire 6
        { id = 1309635, level = 48, tab = 3, rank = 3, prev = 1309633 }, -- Shadow Word: Death 3
        { id = 1277639, level = 50, tab = 1, rank = 4, prev = 1277638 }, -- Contingency Plan 4
        { id = 14819, level = 50, tab = 1, rank = 3, cost = 1500, prev = 14818 }, -- Divine Spirit 3
        { id = 19274, level = 50, tab = 1, rank = 4, prev = 19273, race = 1 }, -- Feedback 4
        { id = 10951, level = 50, tab = 1, rank = 5, cost = 30000, prev = 1006 }, -- Inner Fire 5
        { id = 1240721, level = 50, tab = 1, rank = 3, prev = 1240720, requires = 402174 }, -- Penance 3
        { id = 19304, level = 50, tab = 1, rank = 6, cost = 1500, prev = 19303, race = 4 }, -- Starshards 6
        { id = 1240773, level = 50, tab = 2, rank = 5, prev = 1240772, requires = 401937 }, -- Binding Heal 5
        { id = 1277334, level = 50, tab = 2, rank = 4, prev = 1277333 }, -- Chastise 4
        { id = 19242, level = 50, tab = 2, rank = 6, cost = 1500, prev = 19241 }, -- Desperate Prayer 6
        { id = 1277377, level = 50, tab = 2, rank = 6, prev = 1277376 }, -- Divine Grace 6
        { id = 10916, level = 50, tab = 2, rank = 6, cost = 30000, prev = 10915 }, -- Flash Heal 6
        { id = 27870, level = 50, tab = 2, rank = 2, cost = 1200, prev = 724 }, -- Lightwell 2
        { id = 10960, level = 50, tab = 2, rank = 3, cost = 30000, prev = 996 }, -- Prayer of Healing 3
        { id = 1240826, level = 50, tab = 2, rank = 2, prev = 401859, requires = 401859 }, -- Prayer of Mending 2
        { id = 10928, level = 50, tab = 2, rank = 8, cost = 30000, prev = 10927 }, -- Renew 8
        { id = 1277327, level = 50, tab = 3, rank = 4, prev = 1277326 }, -- Dark Sacrifice 4
        { id = 10941, level = 50, tab = 3, rank = 5, cost = 30000, prev = 9592 }, -- Fade 5
        { id = 19284, level = 50, tab = 3, rank = 5, cost = 1500, prev = 19283, race = 8 }, -- Hex of Weakness 5
        { id = 10893, level = 50, tab = 3, rank = 7, cost = 30000, prev = 10892 }, -- Shadow Word: Pain 7
        { id = 19265, level = 50, tab = 3, rank = 5, cost = 1500, prev = 19264, race = 5 }, -- Touch of Weakness 5
        { id = 10964, level = 52, tab = 2, rank = 3, cost = 38000, prev = 10963 }, -- Greater Heal 3
        { id = 27800, level = 52, tab = 2, rank = 5, cost = 1900, prev = 27799, requires = 15237 }, -- Holy Nova 5
        { id = 19279, level = 52, tab = 3, rank = 5, cost = 1900, prev = 19278 }, -- Devouring Plague 5
        { id = 10946, level = 52, tab = 3, rank = 8, cost = 38000, prev = 10945 }, -- Mind Blast 8
        { id = 17314, level = 52, tab = 3, rank = 5, cost = 1900, prev = 17313, requires = 15407 }, -- Mind Flay 5
        { id = 10953, level = 52, tab = 3, rank = 3, cost = 38000, prev = 8192 }, -- Mind Soothe 3
        { id = 19311, level = 52, tab = 3, rank = 5, cost = 1200, prev = 19310, race = 8 }, -- Shadowguard 5
        { id = 10900, level = 54, tab = 1, rank = 9, cost = 40000, prev = 10899 }, -- Power Word: Shield 9
        { id = 15267, level = 54, tab = 2, rank = 7, cost = 40000, prev = 15266 }, -- Holy Fire 7
        { id = 10934, level = 54, tab = 2, rank = 8, cost = 40000, prev = 10933 }, -- Smite 8
        { id = 10876, level = 56, tab = 1, rank = 5, cost = 42000, prev = 10875 }, -- Mana Burn 5
        { id = 1240774, level = 56, tab = 2, rank = 6, prev = 1240773, requires = 401937 }, -- Binding Heal 6
        { id = 10917, level = 56, tab = 2, rank = 7, cost = 42000, prev = 10916 }, -- Flash Heal 7
        { id = 10929, level = 56, tab = 2, rank = 9, cost = 42000, prev = 10928 }, -- Renew 9
        { id = 27683, level = 56, tab = 3, rank = 1, book = 22393 }, -- Prayer of Shadow Protection 1
        { id = 10890, level = 56, tab = 3, rank = 4, cost = 42000, prev = 10888 }, -- Psychic Scream 4
        { id = 10958, level = 56, tab = 3, rank = 3, cost = 42000, prev = 10957 }, -- Shadow Protection 3
        { id = 1309636, level = 56, tab = 3, rank = 4, prev = 1309635 }, -- Shadow Word: Death 4
        { id = 19305, level = 58, tab = 1, rank = 7, cost = 2200, prev = 19304, race = 4 }, -- Starshards 7
        { id = 19243, level = 58, tab = 2, rank = 7, cost = 2200, prev = 19242 }, -- Desperate Prayer 7
        { id = 1277378, level = 58, tab = 2, rank = 7, prev = 1277377 }, -- Divine Grace 7
        { id = 10965, level = 58, tab = 2, rank = 4, cost = 44000, prev = 10964 }, -- Greater Heal 4
        { id = 20770, level = 58, tab = 2, rank = 5, cost = 44000, prev = 10881 }, -- Resurrection 5
        { id = 10947, level = 58, tab = 3, rank = 9, cost = 44000, prev = 10946 }, -- Mind Blast 9
        { id = 10912, level = 58, tab = 3, rank = 3, cost = 44000, prev = 10911 }, -- Mind Control 3
        { id = 10894, level = 58, tab = 3, rank = 8, cost = 44000, prev = 10893 }, -- Shadow Word: Pain 8
        { id = 1277640, level = 60, tab = 1, rank = 5, prev = 1277639 }, -- Contingency Plan 5
        { id = 27841, level = 60, tab = 1, rank = 4, cost = 2300, prev = 14819 }, -- Divine Spirit 4
        { id = 19275, level = 60, tab = 1, rank = 5, prev = 19274, race = 1 }, -- Feedback 5
        { id = 10952, level = 60, tab = 1, rank = 6, cost = 46000, prev = 10951 }, -- Inner Fire 6
        { id = 1316991, level = 60, tab = 1, rank = 4, prev = 1240721, requires = 402174 }, -- Penance 4
        { id = 10938, level = 60, tab = 1, rank = 6, cost = 46000, prev = 10937 }, -- Power Word: Fortitude 6
        { id = 10901, level = 60, tab = 1, rank = 10, cost = 46000, prev = 10900 }, -- Power Word: Shield 10
        { id = 21564, level = 60, tab = 1, rank = 2, book = 17414, prev = 21562 }, -- Prayer of Fortitude 2
        { id = 27681, level = 60, tab = 1, rank = 1, cost = 2300, needs = { 27841 } }, -- Prayer of Spirit 1
        { id = 10955, level = 60, tab = 1, rank = 3, cost = 46000, prev = 9485 }, -- Shackle Undead 3
        { id = 1277335, level = 60, tab = 2, rank = 5, prev = 1277334 }, -- Chastise 5
        { id = 25314, level = 60, tab = 2, rank = 5, book = 21284, prev = 10965 }, -- Greater Heal 5
        { id = 15261, level = 60, tab = 2, rank = 8, cost = 46000, prev = 15267 }, -- Holy Fire 8
        { id = 27801, level = 60, tab = 2, rank = 6, cost = 2300, prev = 27800, requires = 15237 }, -- Holy Nova 6
        { id = 27871, level = 60, tab = 2, rank = 3, cost = 1500, prev = 27870 }, -- Lightwell 3
        { id = 10961, level = 60, tab = 2, rank = 4, cost = 46000, prev = 10960 }, -- Prayer of Healing 4
        { id = 25316, level = 60, tab = 2, rank = 5, book = 21287, prev = 10961 }, -- Prayer of Healing 5
        { id = 1240827, level = 60, tab = 2, rank = 3, prev = 1240826, requires = 401859 }, -- Prayer of Mending 3
        { id = 25315, level = 60, tab = 2, rank = 10, book = 21285, prev = 10929 }, -- Renew 10
        { id = 1277328, level = 60, tab = 3, rank = 5, prev = 1277327 }, -- Dark Sacrifice 5
        { id = 19280, level = 60, tab = 3, rank = 6, cost = 2300, prev = 19279 }, -- Devouring Plague 6
        { id = 10942, level = 60, tab = 3, rank = 6, cost = 46000, prev = 10941 }, -- Fade 6
        { id = 19285, level = 60, tab = 3, rank = 6, cost = 2300, prev = 19284, race = 8 }, -- Hex of Weakness 6
        { id = 18807, level = 60, tab = 3, rank = 6, cost = 2300, prev = 17314, requires = 15407 }, -- Mind Flay 6
        { id = 19312, level = 60, tab = 3, rank = 6, cost = 2300, prev = 19311, race = 8 }, -- Shadowguard 6
        { id = 19266, level = 60, tab = 3, rank = 6, cost = 2070, prev = 19265, race = 5 }, -- Touch of Weakness 6
    },
}
