-- Generated by tools/build_data.py. Do not edit by hand.
-- Forever client build 1.60.1.69876.
local _, SBE = ...

SBE.Data.ROGUE = {
    tabs = { "Assassination", "Combat", "Subtlety", "Poisons", "General" },
    spells = {
        { id = 1784, level = 1, tab = 3, rank = 1, cost = 10 }, -- Stealth 1
        { id = 53, level = 4, tab = 2, rank = 1, cost = 100 }, -- Backstab 1
        { id = 921, level = 4, tab = 3, cost = 100 }, -- Pick Pocket
        { id = 1776, level = 6, tab = 2, rank = 1, cost = 100 }, -- Gouge 1
        { id = 1757, level = 6, tab = 2, rank = 2, cost = 100, prev = 1752 }, -- Sinister Strike 2
        { id = 6760, level = 8, tab = 1, rank = 2, cost = 200, prev = 2098 }, -- Eviscerate 2
        { id = 5277, level = 8, tab = 2, cost = 200 }, -- Evasion
        { id = 5171, level = 10, tab = 1, rank = 1, cost = 300 }, -- Slice and Dice 1
        { id = 2983, level = 10, tab = 2, rank = 1, cost = 300 }, -- Sprint 1
        { id = 674, level = 10, tab = 5, cost = 300, general = true }, -- Dual Wield
        { id = 6770, level = 10, tab = 3, rank = 1, cost = 300 }, -- Sap 1
        { id = 2589, level = 12, tab = 2, rank = 2, cost = 800, prev = 53 }, -- Backstab 2
        { id = 1766, level = 12, tab = 2, rank = 1, cost = 800 }, -- Kick 1
        { id = 3127, level = 12, tab = 5, cost = 800, general = true }, -- Parry
        { id = 8647, level = 14, tab = 1, rank = 1, cost = 1200 }, -- Expose Armor 1
        { id = 703, level = 14, tab = 1, rank = 1, cost = 1200 }, -- Garrote 1
        { id = 1758, level = 14, tab = 2, rank = 3, cost = 1200, prev = 1757 }, -- Sinister Strike 3
        { id = 6761, level = 16, tab = 1, rank = 3, cost = 1800, prev = 6760 }, -- Eviscerate 3
        { id = 1966, level = 16, tab = 2, rank = 1, cost = 1800 }, -- Feint 1
        { id = 8676, level = 18, tab = 1, rank = 1, cost = 2900 }, -- Ambush 1
        { id = 1777, level = 18, tab = 2, rank = 2, cost = 2900, prev = 1776 }, -- Gouge 2
        { id = 1943, level = 20, tab = 1, rank = 1, cost = 3000 }, -- Rupture 1
        { id = 2590, level = 20, tab = 2, rank = 3, cost = 3000, prev = 2589 }, -- Backstab 3
        { id = 3420, level = 20, tab = 4, rank = 1, cost = 3000 }, -- Crippling Poison 1
        { id = 8681, level = 20, tab = 4, rank = 1, quest = true }, -- Instant Poison 1
        { id = 2842, level = 20, tab = 4, quest = true }, -- Poisons
        { id = 1785, level = 20, tab = 3, rank = 2, cost = 3000, prev = 1784 }, -- Stealth 2
        { id = 8631, level = 22, tab = 1, rank = 2, cost = 4000, prev = 703 }, -- Garrote 2
        { id = 1759, level = 22, tab = 2, rank = 4, cost = 4000, prev = 1758 }, -- Sinister Strike 4
        { id = 1725, level = 22, tab = 3, cost = 4000 }, -- Distract
        { id = 1856, level = 22, tab = 3, rank = 1, cost = 4000, needs = { 1784 } }, -- Vanish 1
        { id = 6762, level = 24, tab = 1, rank = 4, cost = 5000, prev = 6761 }, -- Eviscerate 4
        { id = 5763, level = 24, tab = 4, rank = 1, cost = 5000, skill = 100 }, -- Mind-numbing Poison 1
        { id = 2836, level = 24, tab = 3, cost = 5000 }, -- Detect Traps
        { id = 8724, level = 26, tab = 1, rank = 2, cost = 6000, prev = 8676 }, -- Ambush 2
        { id = 1833, level = 26, tab = 1, cost = 6000 }, -- Cheap Shot
        { id = 8649, level = 26, tab = 1, rank = 2, cost = 6000, prev = 8647 }, -- Expose Armor 2
        { id = 1767, level = 26, tab = 2, rank = 2, cost = 6000, prev = 1766 }, -- Kick 2
        { id = 8639, level = 28, tab = 1, rank = 2, cost = 8000, prev = 1943 }, -- Rupture 2
        { id = 2591, level = 28, tab = 2, rank = 4, cost = 8000, prev = 2590 }, -- Backstab 4
        { id = 6768, level = 28, tab = 2, rank = 2, cost = 8000, prev = 1966 }, -- Feint 2
        { id = 8687, level = 28, tab = 4, rank = 2, cost = 8000, skill = 120 }, -- Instant Poison II 2
        { id = 2070, level = 28, tab = 3, rank = 2, cost = 8000, prev = 6770 }, -- Sap 2
        { id = 1310709, level = 30, tab = 1 }, -- Coup de Grace
        { id = 8632, level = 30, tab = 1, rank = 3, cost = 10000, prev = 8631 }, -- Garrote 3
        { id = 408, level = 30, tab = 1, rank = 1, cost = 10000 }, -- Kidney Shot 1
        { id = 1760, level = 30, tab = 2, rank = 5, cost = 10000, prev = 1759 }, -- Sinister Strike 5
        { id = 2835, level = 30, tab = 4, rank = 1, cost = 10000, skill = 130 }, -- Deadly Poison 1
        { id = 1842, level = 30, tab = 3, cost = 10000, needs = { 2836 } }, -- Disarm Trap
        { id = 8623, level = 32, tab = 1, rank = 5, cost = 12000, prev = 6762 }, -- Eviscerate 5
        { id = 8629, level = 32, tab = 2, rank = 3, cost = 12000, prev = 1777 }, -- Gouge 3
        { id = 13220, level = 32, tab = 4, rank = 1, cost = 12000, skill = 140 }, -- Wound Poison 1
        { id = 8725, level = 34, tab = 1, rank = 3, cost = 14000, prev = 8724 }, -- Ambush 3
        { id = 8696, level = 34, tab = 2, rank = 2, cost = 14000, prev = 2983 }, -- Sprint 2
        { id = 6510, level = 34, tab = 4, cost = 14000, skill = 150 }, -- Blinding Powder
        { id = 2094, level = 34, tab = 3, cost = 14000 }, -- Blind
        { id = 8650, level = 36, tab = 1, rank = 3, cost = 16000, prev = 8649 }, -- Expose Armor 3
        { id = 8640, level = 36, tab = 1, rank = 3, cost = 16000, prev = 8639 }, -- Rupture 3
        { id = 8721, level = 36, tab = 2, rank = 5, cost = 16000, prev = 2591 }, -- Backstab 5
        { id = 8691, level = 36, tab = 4, rank = 3, cost = 16000, skill = 160 }, -- Instant Poison III 3
        { id = 8633, level = 38, tab = 1, rank = 4, cost = 18000, prev = 8632 }, -- Garrote 4
        { id = 8621, level = 38, tab = 2, rank = 6, cost = 18000, prev = 1760 }, -- Sinister Strike 6
        { id = 2837, level = 38, tab = 4, rank = 2, cost = 18000, skill = 170 }, -- Deadly Poison II 2
        { id = 8694, level = 38, tab = 4, rank = 2, cost = 18000, skill = 170 }, -- Mind-numbing Poison II 2
        { id = 8624, level = 40, tab = 1, rank = 6, cost = 20000, prev = 8623 }, -- Eviscerate 6
        { id = 399956, level = 40, tab = 1, rank = 2, prev = 1310707, requires = 1310707 }, -- Mutilate 2
        { id = 8637, level = 40, tab = 2, rank = 3, cost = 20000, prev = 6768 }, -- Feint 3
        { id = 13228, level = 40, tab = 4, rank = 2, cost = 20000, skill = 180 }, -- Wound Poison II 2
        { id = 1860, level = 40, tab = 3, cost = 20000 }, -- Safe Fall
        { id = 1786, level = 40, tab = 3, rank = 3, cost = 20000, prev = 1785 }, -- Stealth 3
        { id = 11267, level = 42, tab = 1, rank = 4, cost = 27000, prev = 8725 }, -- Ambush 4
        { id = 6774, level = 42, tab = 1, rank = 2, cost = 27000, prev = 5171 }, -- Slice and Dice 2
        { id = 1768, level = 42, tab = 2, rank = 3, cost = 27000, prev = 1767 }, -- Kick 3
        { id = 1857, level = 42, tab = 3, rank = 2, cost = 27000, prev = 1856 }, -- Vanish 2
        { id = 11273, level = 44, tab = 1, rank = 4, cost = 29000, prev = 8640 }, -- Rupture 4
        { id = 11279, level = 44, tab = 2, rank = 6, cost = 29000, prev = 8721 }, -- Backstab 6
        { id = 11341, level = 44, tab = 4, rank = 4, cost = 29000, skill = 200 }, -- Instant Poison IV 4
        { id = 11197, level = 46, tab = 1, rank = 4, cost = 31000, prev = 8650 }, -- Expose Armor 4
        { id = 11289, level = 46, tab = 1, rank = 5, cost = 31000, prev = 8633 }, -- Garrote 5
        { id = 11285, level = 46, tab = 2, rank = 4, cost = 31000, prev = 8629 }, -- Gouge 4
        { id = 11293, level = 46, tab = 2, rank = 7, cost = 31000, prev = 8621 }, -- Sinister Strike 7
        { id = 11357, level = 46, tab = 4, rank = 3, cost = 31000, skill = 210 }, -- Deadly Poison III 3
        { id = 11299, level = 48, tab = 1, rank = 7, cost = 33000, prev = 8624 }, -- Eviscerate 7
        { id = 13229, level = 48, tab = 4, rank = 3, cost = 33000, skill = 220 }, -- Wound Poison III 3
        { id = 11297, level = 48, tab = 3, rank = 3, cost = 33000, prev = 2070 }, -- Sap 3
        { id = 11268, level = 50, tab = 1, rank = 5, cost = 35000, prev = 11267 }, -- Ambush 5
        { id = 8643, level = 50, tab = 1, rank = 2, cost = 35000, prev = 408 }, -- Kidney Shot 2
        { id = 1241582, level = 50, tab = 1, rank = 3, prev = 399956, requires = 1310707 }, -- Mutilate 3
        { id = 3421, level = 50, tab = 4, rank = 2, cost = 35000, skill = 230 }, -- Crippling Poison II 2
        { id = 11274, level = 52, tab = 1, rank = 5, cost = 46000, prev = 11273 }, -- Rupture 5
        { id = 11280, level = 52, tab = 2, rank = 7, cost = 46000, prev = 11279 }, -- Backstab 7
        { id = 11303, level = 52, tab = 2, rank = 4, cost = 46000, prev = 8637 }, -- Feint 4
        { id = 11342, level = 52, tab = 4, rank = 5, cost = 46000, skill = 240 }, -- Instant Poison V 5
        { id = 11400, level = 52, tab = 4, rank = 3, cost = 46000, skill = 240 }, -- Mind-numbing Poison III 3
        { id = 11290, level = 54, tab = 1, rank = 6, cost = 48000, prev = 11289 }, -- Garrote 6
        { id = 11294, level = 54, tab = 2, rank = 8, cost = 48000, prev = 11293 }, -- Sinister Strike 8
        { id = 11358, level = 54, tab = 4, rank = 4, cost = 48000, skill = 250 }, -- Deadly Poison IV 4
        { id = 11300, level = 56, tab = 1, rank = 8, cost = 50000, prev = 11299 }, -- Eviscerate 8
        { id = 11198, level = 56, tab = 1, rank = 5, cost = 50000, prev = 11197 }, -- Expose Armor 5
        { id = 13230, level = 56, tab = 4, rank = 4, cost = 50000, skill = 260 }, -- Wound Poison IV 4
        { id = 11269, level = 58, tab = 1, rank = 6, cost = 52000, prev = 11268 }, -- Ambush 6
        { id = 1769, level = 58, tab = 2, rank = 4, cost = 52000, prev = 1768 }, -- Kick 4
        { id = 11305, level = 58, tab = 2, rank = 3, cost = 52000, prev = 8696 }, -- Sprint 3
        { id = 31016, level = 60, tab = 1, rank = 9, book = 24102, prev = 11300 }, -- Eviscerate 9
        { id = 1241584, level = 60, tab = 1, rank = 4, prev = 1241582, requires = 1310707 }, -- Mutilate 4
        { id = 11275, level = 60, tab = 1, rank = 6, cost = 54000, prev = 11274 }, -- Rupture 6
        { id = 11281, level = 60, tab = 2, rank = 8, cost = 54000, prev = 11280 }, -- Backstab 8
        { id = 25300, level = 60, tab = 2, rank = 9, book = 21300, prev = 11281 }, -- Backstab 9
        { id = 25302, level = 60, tab = 2, rank = 5, book = 21303, prev = 11303 }, -- Feint 5
        { id = 11286, level = 60, tab = 2, rank = 5, cost = 54000, prev = 11285 }, -- Gouge 5
        { id = 25347, level = 60, tab = 4, rank = 5, book = 21302 }, -- Deadly Poison V 5
        { id = 11343, level = 60, tab = 4, rank = 6, cost = 54000, skill = 280 }, -- Instant Poison VI 6
        { id = 1787, level = 60, tab = 3, rank = 4, cost = 54000, prev = 1786 }, -- Stealth 4
    },
}
