-- Generated by tools/build_data.py. Do not edit by hand.
-- Forever client build 1.60.1.69876.
local _, SBE = ...

SBE.Data.SHAMAN = {
    tabs = { "Elemental Combat", "Enhancement", "Restoration", "General" },
    spells = {
        { id = 8017, level = 1, tab = 2, rank = 1, cost = 10 }, -- Rockbiter Weapon 1
        { id = 8042, level = 4, tab = 1, rank = 1, cost = 100 }, -- Earth Shock 1
        { id = 8071, level = 4, tab = 2, rank = 1, quest = true }, -- Stoneskin Totem 1
        { id = 2484, level = 6, tab = 1, cost = 100 }, -- Earthbind Totem
        { id = 332, level = 6, tab = 3, rank = 2, cost = 100, prev = 331 }, -- Healing Wave 2
        { id = 8044, level = 8, tab = 1, rank = 2, cost = 100, prev = 8042 }, -- Earth Shock 2
        { id = 529, level = 8, tab = 1, rank = 2, cost = 100, prev = 403 }, -- Lightning Bolt 2
        { id = 5730, level = 8, tab = 1, rank = 1, cost = 100 }, -- Stoneclaw Totem 1
        { id = 324, level = 8, tab = 2, rank = 1, cost = 100 }, -- Lightning Shield 1
        { id = 8018, level = 8, tab = 2, rank = 2, cost = 100, prev = 8017 }, -- Rockbiter Weapon 2
        { id = 8050, level = 10, tab = 1, rank = 1, cost = 400 }, -- Flame Shock 1
        { id = 3599, level = 10, tab = 1, rank = 1, quest = true }, -- Searing Totem 1
        { id = 8024, level = 10, tab = 2, rank = 1, cost = 400 }, -- Flametongue Weapon 1
        { id = 8075, level = 10, tab = 2, rank = 1, cost = 400 }, -- Strength of Earth Totem 1
        { id = 370, level = 12, tab = 1, rank = 1, cost = 720 }, -- Purge 1
        { id = 2008, level = 12, tab = 3, rank = 1, cost = 800 }, -- Ancestral Spirit 1
        { id = 547, level = 12, tab = 3, rank = 3, cost = 800, prev = 332 }, -- Healing Wave 3
        { id = 8045, level = 14, tab = 1, rank = 3, cost = 900, prev = 8044 }, -- Earth Shock 3
        { id = 548, level = 14, tab = 1, rank = 3, cost = 900, prev = 529 }, -- Lightning Bolt 3
        { id = 8154, level = 14, tab = 2, rank = 2, cost = 900, prev = 8071 }, -- Stoneskin Totem 2
        { id = 325, level = 16, tab = 2, rank = 2, cost = 1800, prev = 324 }, -- Lightning Shield 2
        { id = 8019, level = 16, tab = 2, rank = 3, cost = 1800, prev = 8018 }, -- Rockbiter Weapon 3
        { id = 526, level = 16, tab = 3, cost = 1800 }, -- Cure Poison
        { id = 8052, level = 18, tab = 1, rank = 2, cost = 2000, prev = 8050 }, -- Flame Shock 2
        { id = 6390, level = 18, tab = 1, rank = 2, cost = 2000, prev = 5730 }, -- Stoneclaw Totem 2
        { id = 8027, level = 18, tab = 2, rank = 2, cost = 2000, prev = 8024 }, -- Flametongue Weapon 2
        { id = 913, level = 18, tab = 3, rank = 4, cost = 2000, prev = 547 }, -- Healing Wave 4
        { id = 8143, level = 18, tab = 3, cost = 2000 }, -- Tremor Totem
        { id = 66842, level = 20, tab = 1 }, -- Call of the Elements
        { id = 8056, level = 20, tab = 1, rank = 1, cost = 2200 }, -- Frost Shock 1
        { id = 915, level = 20, tab = 1, rank = 4, cost = 2200, prev = 548 }, -- Lightning Bolt 4
        { id = 6363, level = 20, tab = 1, rank = 2, cost = 2200, prev = 3599 }, -- Searing Totem 2
        { id = 36936, level = 20, tab = 1 }, -- Totemic Recall
        { id = 8033, level = 20, tab = 2, rank = 1, cost = 2200 }, -- Frostbrand Weapon 1
        { id = 2645, level = 20, tab = 2, cost = 2200 }, -- Ghost Wolf
        { id = 5394, level = 20, tab = 3, rank = 1, quest = true }, -- Healing Stream Totem 1
        { id = 8004, level = 20, tab = 3, rank = 1, cost = 2200 }, -- Lesser Healing Wave 1
        { id = 131, level = 22, tab = 2, cost = 3000 }, -- Water Breathing
        { id = 2870, level = 22, tab = 3, cost = 900 }, -- Cure Disease
        { id = 8166, level = 22, tab = 3, cost = 3000 }, -- Poison Cleansing Totem
        { id = 8046, level = 24, tab = 1, rank = 4, cost = 3500, prev = 8045 }, -- Earth Shock 4
        { id = 8181, level = 24, tab = 2, rank = 1, cost = 3500 }, -- Frost Resistance Totem 1
        { id = 905, level = 24, tab = 2, rank = 3, cost = 3500, prev = 325 }, -- Lightning Shield 3
        { id = 10399, level = 24, tab = 2, rank = 4, cost = 3500, prev = 8019 }, -- Rockbiter Weapon 4
        { id = 8155, level = 24, tab = 2, rank = 3, cost = 3500, prev = 8154 }, -- Stoneskin Totem 3
        { id = 8160, level = 24, tab = 2, rank = 2, cost = 3500, prev = 8075 }, -- Strength of Earth Totem 2
        { id = 20609, level = 24, tab = 3, rank = 2, cost = 3500, prev = 2008 }, -- Ancestral Spirit 2
        { id = 939, level = 24, tab = 3, rank = 5, cost = 3500, prev = 913 }, -- Healing Wave 5
        { id = 943, level = 26, tab = 1, rank = 5, cost = 4000, prev = 915 }, -- Lightning Bolt 5
        { id = 8190, level = 26, tab = 1, rank = 1, cost = 4000 }, -- Magma Totem 1
        { id = 6196, level = 26, tab = 2, cost = 4000 }, -- Far Sight
        { id = 8030, level = 26, tab = 2, rank = 3, cost = 4000, prev = 8027 }, -- Flametongue Weapon 3
        { id = 5675, level = 26, tab = 3, rank = 1, cost = 4000 }, -- Mana Spring Totem 1
        { id = 8053, level = 28, tab = 1, rank = 3, cost = 6000, prev = 8052 }, -- Flame Shock 3
        { id = 6391, level = 28, tab = 1, rank = 3, cost = 6000, prev = 6390 }, -- Stoneclaw Totem 3
        { id = 8184, level = 28, tab = 2, rank = 1, cost = 6000 }, -- Fire Resistance Totem 1
        { id = 8227, level = 28, tab = 2, rank = 1, cost = 6000 }, -- Flametongue Totem 1
        { id = 8038, level = 28, tab = 2, rank = 2, cost = 6000, prev = 8033 }, -- Frostbrand Weapon 2
        { id = 546, level = 28, tab = 2, cost = 6000 }, -- Water Walking
        { id = 8008, level = 28, tab = 3, rank = 2, cost = 6000, prev = 8004 }, -- Lesser Healing Wave 2
        { id = 66843, level = 30, tab = 1 }, -- Call of the Ancestors
        { id = 6364, level = 30, tab = 1, rank = 3, cost = 7000, prev = 6363 }, -- Searing Totem 3
        { id = 556, level = 30, tab = 2, cost = 7000 }, -- Astral Recall
        { id = 8177, level = 30, tab = 2, cost = 7000 }, -- Grounding Totem
        { id = 10595, level = 30, tab = 2, rank = 1, cost = 7000 }, -- Nature Resistance Totem 1
        { id = 8232, level = 30, tab = 2, rank = 1, cost = 7000 }, -- Windfury Weapon 1
        { id = 6375, level = 30, tab = 3, rank = 2, cost = 7000, prev = 5394 }, -- Healing Stream Totem 2
        { id = 20608, level = 30, tab = 3, cost = 7000 }, -- Reincarnation
        { id = 421, level = 32, tab = 1, rank = 1, cost = 8000 }, -- Chain Lightning 1
        { id = 6041, level = 32, tab = 1, rank = 6, cost = 8000, prev = 943 }, -- Lightning Bolt 6
        { id = 8012, level = 32, tab = 1, rank = 2, cost = 7200, prev = 370 }, -- Purge 2
        { id = 945, level = 32, tab = 2, rank = 4, cost = 8000, prev = 905 }, -- Lightning Shield 4
        { id = 8512, level = 32, tab = 2, rank = 1, cost = 8000 }, -- Windfury Totem 1
        { id = 959, level = 32, tab = 3, rank = 6, cost = 8000, prev = 939 }, -- Healing Wave 6
        { id = 8058, level = 34, tab = 1, rank = 2, cost = 9000, prev = 8056 }, -- Frost Shock 2
        { id = 16314, level = 34, tab = 2, rank = 5, cost = 9000, prev = 10399 }, -- Rockbiter Weapon 5
        { id = 6495, level = 34, tab = 2, cost = 9000 }, -- Sentry Totem
        { id = 10406, level = 34, tab = 2, rank = 4, cost = 9000, prev = 8155 }, -- Stoneskin Totem 4
        { id = 10412, level = 36, tab = 1, rank = 5, cost = 10000, prev = 8046 }, -- Earth Shock 5
        { id = 10585, level = 36, tab = 1, rank = 2, cost = 10000, prev = 8190 }, -- Magma Totem 2
        { id = 16339, level = 36, tab = 2, rank = 4, cost = 10000, prev = 8030 }, -- Flametongue Weapon 4
        { id = 15107, level = 36, tab = 2, rank = 1, cost = 10000 }, -- Windwall Totem 1
        { id = 20610, level = 36, tab = 3, rank = 3, cost = 10000, prev = 20609 }, -- Ancestral Spirit 3
        { id = 8010, level = 36, tab = 3, rank = 3, cost = 10000, prev = 8008 }, -- Lesser Healing Wave 3
        { id = 10495, level = 36, tab = 3, rank = 2, cost = 10000, prev = 5675 }, -- Mana Spring Totem 2
        { id = 10391, level = 38, tab = 1, rank = 7, cost = 11000, prev = 6041 }, -- Lightning Bolt 7
        { id = 6392, level = 38, tab = 1, rank = 4, cost = 11000, prev = 6391 }, -- Stoneclaw Totem 4
        { id = 8249, level = 38, tab = 2, rank = 2, cost = 11000, prev = 8227 }, -- Flametongue Totem 2
        { id = 10478, level = 38, tab = 2, rank = 2, cost = 11000, prev = 8181 }, -- Frost Resistance Totem 2
        { id = 10456, level = 38, tab = 2, rank = 3, cost = 11000, prev = 8038 }, -- Frostbrand Weapon 3
        { id = 8161, level = 38, tab = 2, rank = 3, cost = 11000, prev = 8160 }, -- Strength of Earth Totem 3
        { id = 8170, level = 38, tab = 3, cost = 11000 }, -- Disease Cleansing Totem
        { id = 66844, level = 40, tab = 1 }, -- Call of the Spirits
        { id = 930, level = 40, tab = 1, rank = 2, cost = 12000, prev = 421 }, -- Chain Lightning 2
        { id = 10447, level = 40, tab = 1, rank = 4, cost = 12000, prev = 8053 }, -- Flame Shock 4
        { id = 6365, level = 40, tab = 1, rank = 4, cost = 12000, prev = 6364 }, -- Searing Totem 4
        { id = 8134, level = 40, tab = 2, rank = 5, cost = 12000, prev = 945 }, -- Lightning Shield 5
        { id = 8235, level = 40, tab = 2, rank = 2, cost = 12000, prev = 8232 }, -- Windfury Weapon 2
        { id = 8737, level = 40, tab = 4, cost = 12000, general = true }, -- Mail
        { id = 1064, level = 40, tab = 3, rank = 1, cost = 12000 }, -- Chain Heal 1
        { id = 6377, level = 40, tab = 3, rank = 3, cost = 12000, prev = 6375 }, -- Healing Stream Totem 3
        { id = 8005, level = 40, tab = 3, rank = 7, cost = 12000, prev = 959 }, -- Healing Wave 7
        { id = 10537, level = 42, tab = 2, rank = 2, cost = 16000, prev = 8184 }, -- Fire Resistance Totem 2
        { id = 8835, level = 42, tab = 2, rank = 1, cost = 16000 }, -- Grace of Air Totem 1
        { id = 10613, level = 42, tab = 2, rank = 2, cost = 16000, prev = 8512 }, -- Windfury Totem 2
        { id = 10392, level = 44, tab = 1, rank = 8, cost = 18000, prev = 10391 }, -- Lightning Bolt 8
        { id = 10600, level = 44, tab = 2, rank = 2, cost = 18000, prev = 10595 }, -- Nature Resistance Totem 2
        { id = 16315, level = 44, tab = 2, rank = 6, cost = 18000, prev = 16314 }, -- Rockbiter Weapon 6
        { id = 10407, level = 44, tab = 2, rank = 5, cost = 18000, prev = 10406 }, -- Stoneskin Totem 5
        { id = 10466, level = 44, tab = 3, rank = 4, cost = 18000, prev = 8010 }, -- Lesser Healing Wave 4
        { id = 10472, level = 46, tab = 1, rank = 3, cost = 20000, prev = 8058 }, -- Frost Shock 3
        { id = 10586, level = 46, tab = 1, rank = 3, cost = 20000, prev = 10585 }, -- Magma Totem 3
        { id = 16341, level = 46, tab = 2, rank = 5, cost = 20000, prev = 16339 }, -- Flametongue Weapon 5
        { id = 15111, level = 46, tab = 2, rank = 2, cost = 20000, prev = 15107 }, -- Windwall Totem 2
        { id = 10622, level = 46, tab = 3, rank = 2, cost = 20000, prev = 1064 }, -- Chain Heal 2
        { id = 10496, level = 46, tab = 3, rank = 3, cost = 20000, prev = 10495 }, -- Mana Spring Totem 3
        { id = 2860, level = 48, tab = 1, rank = 3, cost = 22000, prev = 930 }, -- Chain Lightning 3
        { id = 10413, level = 48, tab = 1, rank = 6, cost = 22000, prev = 10412 }, -- Earth Shock 6
        { id = 10427, level = 48, tab = 1, rank = 5, cost = 22000, prev = 6392 }, -- Stoneclaw Totem 5
        { id = 10526, level = 48, tab = 2, rank = 3, cost = 22000, prev = 8249 }, -- Flametongue Totem 3
        { id = 16355, level = 48, tab = 2, rank = 4, cost = 22000, prev = 10456 }, -- Frostbrand Weapon 4
        { id = 10431, level = 48, tab = 2, rank = 6, cost = 22000, prev = 8134 }, -- Lightning Shield 6
        { id = 20776, level = 48, tab = 3, rank = 4, cost = 22000, prev = 20610 }, -- Ancestral Spirit 4
        { id = 10395, level = 48, tab = 3, rank = 8, cost = 22000, prev = 8005 }, -- Healing Wave 8
        { id = 17354, level = 48, tab = 3, rank = 2, cost = 55000, prev = 16190, requires = 16190 }, -- Mana Tide Totem 2
        { id = 1238299, level = 50, tab = 1, rank = 2, prev = 408490, requires = 408490 }, -- Lava Burst 2
        { id = 15207, level = 50, tab = 1, rank = 9, cost = 24000, prev = 10392 }, -- Lightning Bolt 9
        { id = 10437, level = 50, tab = 1, rank = 5, cost = 24000, prev = 6365 }, -- Searing Totem 5
        { id = 10486, level = 50, tab = 2, rank = 3, cost = 24000, prev = 8235 }, -- Windfury Weapon 3
        { id = 10462, level = 50, tab = 3, rank = 4, cost = 24000, prev = 6377 }, -- Healing Stream Totem 4
        { id = 1239242, level = 50, tab = 3, rank = 2, prev = 408521, requires = 408521 }, -- Riptide 2
        { id = 10448, level = 52, tab = 1, rank = 5, cost = 27000, prev = 10447 }, -- Flame Shock 5
        { id = 10442, level = 52, tab = 2, rank = 4, cost = 27000, prev = 8161 }, -- Strength of Earth Totem 4
        { id = 10614, level = 52, tab = 2, rank = 3, cost = 27000, prev = 10613 }, -- Windfury Totem 3
        { id = 10467, level = 52, tab = 3, rank = 5, cost = 27000, prev = 10466 }, -- Lesser Healing Wave 5
        { id = 10479, level = 54, tab = 2, rank = 3, cost = 29000, prev = 10478 }, -- Frost Resistance Totem 3
        { id = 16316, level = 54, tab = 2, rank = 7, cost = 29000, prev = 16315 }, -- Rockbiter Weapon 7
        { id = 10408, level = 54, tab = 2, rank = 6, cost = 29000, prev = 10407 }, -- Stoneskin Totem 6
        { id = 10623, level = 54, tab = 3, rank = 3, cost = 29000, prev = 10622 }, -- Chain Heal 3
        { id = 10605, level = 56, tab = 1, rank = 4, cost = 30000, prev = 2860 }, -- Chain Lightning 4
        { id = 15208, level = 56, tab = 1, rank = 10, cost = 30000, prev = 15207 }, -- Lightning Bolt 10
        { id = 10587, level = 56, tab = 1, rank = 4, cost = 30000, prev = 10586 }, -- Magma Totem 4
        { id = 16342, level = 56, tab = 2, rank = 6, cost = 30000, prev = 16341 }, -- Flametongue Weapon 6
        { id = 10627, level = 56, tab = 2, rank = 2, cost = 30000, prev = 8835 }, -- Grace of Air Totem 2
        { id = 10432, level = 56, tab = 2, rank = 7, cost = 30000, prev = 10431 }, -- Lightning Shield 7
        { id = 15112, level = 56, tab = 2, rank = 3, cost = 30000, prev = 15111 }, -- Windwall Totem 3
        { id = 10396, level = 56, tab = 3, rank = 9, cost = 30000, prev = 10395 }, -- Healing Wave 9
        { id = 10497, level = 56, tab = 3, rank = 4, cost = 30000, prev = 10496 }, -- Mana Spring Totem 4
        { id = 10473, level = 58, tab = 1, rank = 4, cost = 32000, prev = 10472 }, -- Frost Shock 4
        { id = 10428, level = 58, tab = 1, rank = 6, cost = 32000, prev = 10427 }, -- Stoneclaw Totem 6
        { id = 10538, level = 58, tab = 2, rank = 3, cost = 32000, prev = 10537 }, -- Fire Resistance Totem 3
        { id = 16387, level = 58, tab = 2, rank = 4, cost = 32000, prev = 10526 }, -- Flametongue Totem 4
        { id = 16356, level = 58, tab = 2, rank = 5, cost = 32000, prev = 16355 }, -- Frostbrand Weapon 5
        { id = 17359, level = 58, tab = 3, rank = 3, cost = 80000, prev = 17354, requires = 16190 }, -- Mana Tide Totem 3
        { id = 10414, level = 60, tab = 1, rank = 7, cost = 34000, prev = 10413 }, -- Earth Shock 7
        { id = 29228, level = 60, tab = 1, rank = 6, book = 23320, prev = 10448 }, -- Flame Shock 6
        { id = 1238300, level = 60, tab = 1, rank = 3, prev = 1238299, requires = 408490 }, -- Lava Burst 3
        { id = 10438, level = 60, tab = 1, rank = 6, cost = 34000, prev = 10437 }, -- Searing Totem 6
        { id = 25359, level = 60, tab = 2, rank = 3, book = 21293, prev = 10627 }, -- Grace of Air Totem 3
        { id = 10601, level = 60, tab = 2, rank = 3, cost = 34000, prev = 10600 }, -- Nature Resistance Totem 3
        { id = 25361, level = 60, tab = 2, rank = 5, book = 21292, prev = 10442 }, -- Strength of Earth Totem 5
        { id = 16362, level = 60, tab = 2, rank = 4, cost = 34000, prev = 10486 }, -- Windfury Weapon 4
        { id = 20777, level = 60, tab = 3, rank = 5, cost = 34000, prev = 20776 }, -- Ancestral Spirit 5
        { id = 10463, level = 60, tab = 3, rank = 5, cost = 34000, prev = 10462 }, -- Healing Stream Totem 5
        { id = 25357, level = 60, tab = 3, rank = 10, book = 21291, prev = 10396 }, -- Healing Wave 10
        { id = 10468, level = 60, tab = 3, rank = 6, cost = 34000, prev = 10467 }, -- Lesser Healing Wave 6
        { id = 1239243, level = 60, tab = 3, rank = 3, prev = 1239242, requires = 408521 }, -- Riptide 3
    },
}
