-- Generated by tools/build_data.py. Do not edit by hand.
-- Forever client build 1.60.1.69876.
local _, SBE = ...

SBE.Data.WARLOCK = {
    tabs = { "Affliction", "Demonology", "Destruction" },
    spells = {
        { id = 348, level = 1, tab = 3, rank = 1, cost = 10 }, -- Immolate 1
        { id = 172, level = 4, tab = 1, rank = 1, cost = 100 }, -- Corruption 1
        { id = 702, level = 4, tab = 1, rank = 1, cost = 100 }, -- Curse of Weakness 1
        { id = 1454, level = 6, tab = 1, rank = 1, cost = 100 }, -- Life Tap 1
        { id = 695, level = 6, tab = 3, rank = 2, cost = 100, prev = 686 }, -- Shadow Bolt 2
        { id = 980, level = 8, tab = 1, rank = 1, cost = 200 }, -- Bane of Agony 1
        { id = 5782, level = 8, tab = 1, rank = 1, cost = 200 }, -- Fear 1
        { id = 1120, level = 10, tab = 1, rank = 1, cost = 300 }, -- Drain Soul 1
        { id = 6201, level = 10, tab = 2, rank = 1, cost = 300, needs = { 1120 } }, -- Create Healthstone 1
        { id = 696, level = 10, tab = 2, rank = 2, cost = 300, prev = 687 }, -- Demon Skin 2
        { id = 697, level = 10, tab = 2, quest = true }, -- Summon Voidwalker
        { id = 707, level = 10, tab = 3, rank = 2, cost = 300, prev = 348 }, -- Immolate 2
        { id = 1108, level = 12, tab = 1, rank = 2, cost = 600, prev = 702 }, -- Curse of Weakness 2
        { id = 755, level = 12, tab = 2, rank = 1, cost = 600 }, -- Health Funnel 1
        { id = 705, level = 12, tab = 3, rank = 3, cost = 600, prev = 695 }, -- Shadow Bolt 3
        { id = 6222, level = 14, tab = 1, rank = 2, cost = 900, prev = 172 }, -- Corruption 2
        { id = 704, level = 14, tab = 1, rank = 1, cost = 900 }, -- Curse of Recklessness 1
        { id = 689, level = 14, tab = 1, rank = 1, cost = 900 }, -- Drain Life 1
        { id = 1455, level = 16, tab = 1, rank = 2, cost = 1200, prev = 1454 }, -- Life Tap 2
        { id = 5697, level = 16, tab = 2, cost = 1200 }, -- Unending Breath
        { id = 1014, level = 18, tab = 1, rank = 2, cost = 1500, prev = 980 }, -- Bane of Agony 2
        { id = 693, level = 18, tab = 2, rank = 1, cost = 1500, needs = { 1120 } }, -- Create Soulstone 1
        { id = 5676, level = 18, tab = 3, rank = 1, cost = 1500 }, -- Searing Pain 1
        { id = 440892, level = 20, tab = 1, rank = 1 }, -- Curse of the Elements 1
        { id = 706, level = 20, tab = 2, rank = 1, cost = 2000 }, -- Demon Armor 1
        { id = 3698, level = 20, tab = 2, rank = 2, cost = 2000, prev = 755 }, -- Health Funnel 2
        { id = 698, level = 20, tab = 2, cost = 2000 }, -- Ritual of Summoning
        { id = 712, level = 20, tab = 2, quest = true }, -- Summon Succubus
        { id = 1094, level = 20, tab = 3, rank = 3, cost = 2000, prev = 707 }, -- Immolate 3
        { id = 5740, level = 20, tab = 3, rank = 1, cost = 2000 }, -- Rain of Fire 1
        { id = 1088, level = 20, tab = 3, rank = 4, cost = 2000, prev = 705 }, -- Shadow Bolt 4
        { id = 6205, level = 22, tab = 1, rank = 3, cost = 2500, prev = 1108 }, -- Curse of Weakness 3
        { id = 699, level = 22, tab = 1, rank = 2, cost = 2500, prev = 689 }, -- Drain Life 2
        { id = 6202, level = 22, tab = 2, rank = 2, cost = 2500, prev = 6201 }, -- Create Healthstone 2
        { id = 126, level = 22, tab = 2, cost = 2500 }, -- Eye of Kilrogg
        { id = 6223, level = 24, tab = 1, rank = 3, cost = 3000, prev = 6222 }, -- Corruption 3
        { id = 5138, level = 24, tab = 1, rank = 1, cost = 3000 }, -- Drain Mana 1
        { id = 8288, level = 24, tab = 1, rank = 2, cost = 3000, prev = 1120 }, -- Drain Soul 2
        { id = 5500, level = 24, tab = 2, cost = 3000 }, -- Sense Demons
        { id = 18867, level = 24, tab = 3, rank = 2, cost = 150, prev = 17877, requires = 17877 }, -- Shadowburn 2
        { id = 1714, level = 26, tab = 1, rank = 1, cost = 4000 }, -- Curse of Tongues 1
        { id = 1456, level = 26, tab = 1, rank = 3, cost = 4000, prev = 1455 }, -- Life Tap 3
        { id = 132, level = 26, tab = 2, rank = 1, cost = 4000 }, -- Detect Invisibility 1
        { id = 17919, level = 26, tab = 3, rank = 2, cost = 4000, prev = 5676 }, -- Searing Pain 2
        { id = 6217, level = 28, tab = 1, rank = 3, cost = 5000, prev = 1014 }, -- Bane of Agony 3
        { id = 7658, level = 28, tab = 1, rank = 2, cost = 5000, prev = 704 }, -- Curse of Recklessness 2
        { id = 710, level = 28, tab = 2, rank = 1, cost = 5000 }, -- Banish 1
        { id = 6366, level = 28, tab = 2, rank = 1, cost = 5000 }, -- Create Firestone 1
        { id = 3699, level = 28, tab = 2, rank = 3, cost = 5000, prev = 3698 }, -- Health Funnel 3
        { id = 1106, level = 28, tab = 3, rank = 5, cost = 5000, prev = 1088 }, -- Shadow Bolt 5
        { id = 1311676, level = 30, tab = 1, rank = 2, prev = 440892 }, -- Curse of the Elements 2
        { id = 709, level = 30, tab = 1, rank = 3, cost = 6000, prev = 699 }, -- Drain Life 3
        { id = 20752, level = 30, tab = 2, rank = 2, cost = 6000, prev = 693 }, -- Create Soulstone 2
        { id = 1086, level = 30, tab = 2, rank = 2, cost = 6000, prev = 706 }, -- Demon Armor 2
        { id = 1098, level = 30, tab = 2, rank = 1, cost = 6000 }, -- Subjugate Demon 1
        { id = 691, level = 30, tab = 2, quest = true }, -- Summon Felhunter
        { id = 1949, level = 30, tab = 3, rank = 1, cost = 6000 }, -- Hellfire 1
        { id = 2941, level = 30, tab = 3, rank = 4, cost = 6000, prev = 1094 }, -- Immolate 4
        { id = 7646, level = 32, tab = 1, rank = 4, cost = 7000, prev = 6205 }, -- Curse of Weakness 4
        { id = 6213, level = 32, tab = 1, rank = 2, cost = 7000, prev = 5782 }, -- Fear 2
        { id = 6229, level = 32, tab = 2, rank = 1, cost = 7000 }, -- Shadow Ward 1
        { id = 1293818, level = 32, tab = 3, rank = 2, prev = 1293817, requires = 1293817 }, -- Conflagrate 2
        { id = 18868, level = 32, tab = 3, rank = 3, cost = 350, prev = 18867, requires = 17877 }, -- Shadowburn 3
        { id = 7648, level = 34, tab = 1, rank = 4, cost = 8000, prev = 6223 }, -- Corruption 4
        { id = 6226, level = 34, tab = 1, rank = 2, cost = 8000, prev = 5138 }, -- Drain Mana 2
        { id = 5699, level = 34, tab = 2, rank = 3, cost = 8000, prev = 6202 }, -- Create Healthstone 3
        { id = 6219, level = 34, tab = 3, rank = 2, cost = 8000, prev = 5740 }, -- Rain of Fire 2
        { id = 17920, level = 34, tab = 3, rank = 3, cost = 8000, prev = 17919 }, -- Searing Pain 3
        { id = 11687, level = 36, tab = 1, rank = 4, cost = 9000, prev = 1456 }, -- Life Tap 4
        { id = 17951, level = 36, tab = 2, rank = 2, cost = 9000, prev = 6366 }, -- Create Firestone 2
        { id = 2362, level = 36, tab = 2, rank = 1, cost = 9000, needs = { 1120 } }, -- Create Spellstone 1
        { id = 3700, level = 36, tab = 2, rank = 4, cost = 9000, prev = 3699 }, -- Health Funnel 4
        { id = 7641, level = 36, tab = 3, rank = 6, cost = 9000, prev = 1106 }, -- Shadow Bolt 6
        { id = 11711, level = 38, tab = 1, rank = 4, cost = 10000, prev = 6217 }, -- Bane of Agony 4
        { id = 7651, level = 38, tab = 1, rank = 4, cost = 10000, prev = 709 }, -- Drain Life 4
        { id = 8289, level = 38, tab = 1, rank = 3, cost = 10000, prev = 8288 }, -- Drain Soul 3
        { id = 18879, level = 38, tab = 1, rank = 2, cost = 500, prev = 18265, requires = 18265 }, -- Siphon Life 2
        { id = 2970, level = 38, tab = 2, rank = 2, cost = 10000, prev = 132 }, -- Detect Invisibility 2
        { id = 1311677, level = 40, tab = 1, rank = 3, prev = 1311676 }, -- Curse of the Elements 3
        { id = 5484, level = 40, tab = 1, rank = 1, cost = 11000 }, -- Howl of Terror 1
        { id = 20755, level = 40, tab = 2, rank = 3, cost = 11000, prev = 20752 }, -- Create Soulstone 3
        { id = 11733, level = 40, tab = 2, rank = 3, cost = 11000, prev = 1086 }, -- Demon Armor 3
        { id = 17962, level = 40, tab = 3, rank = 3, prev = 1293818, requires = 1293817 }, -- Conflagrate 3
        { id = 11665, level = 40, tab = 3, rank = 5, cost = 11000, prev = 2941 }, -- Immolate 5
        { id = 18869, level = 40, tab = 3, rank = 4, cost = 550, prev = 18868, requires = 17877 }, -- Shadowburn 4
        { id = 7659, level = 42, tab = 1, rank = 3, cost = 11000, prev = 7658 }, -- Curse of Recklessness 3
        { id = 11707, level = 42, tab = 1, rank = 5, cost = 11000, prev = 7646 }, -- Curse of Weakness 5
        { id = 6789, level = 42, tab = 1, rank = 1, cost = 11000 }, -- Death Coil 1
        { id = 11739, level = 42, tab = 2, rank = 2, cost = 11000, prev = 6229 }, -- Shadow Ward 2
        { id = 11683, level = 42, tab = 3, rank = 2, cost = 9900, prev = 1949 }, -- Hellfire 2
        { id = 17921, level = 42, tab = 3, rank = 4, cost = 11000, prev = 17920 }, -- Searing Pain 4
        { id = 11671, level = 44, tab = 1, rank = 5, cost = 12000, prev = 7648 }, -- Corruption 5
        { id = 11703, level = 44, tab = 1, rank = 3, cost = 12000, prev = 6226 }, -- Drain Mana 3
        { id = 11693, level = 44, tab = 2, rank = 5, cost = 12000, prev = 3700 }, -- Health Funnel 5
        { id = 11725, level = 44, tab = 2, rank = 2, cost = 12000, prev = 1098 }, -- Subjugate Demon 2
        { id = 11659, level = 44, tab = 3, rank = 7, cost = 12000, prev = 7641 }, -- Shadow Bolt 7
        { id = 11699, level = 46, tab = 1, rank = 5, cost = 13000, prev = 7651 }, -- Drain Life 5
        { id = 11688, level = 46, tab = 1, rank = 5, cost = 13000, prev = 11687 }, -- Life Tap 5
        { id = 17952, level = 46, tab = 2, rank = 3, cost = 13000, prev = 17951 }, -- Create Firestone 3
        { id = 11729, level = 46, tab = 2, rank = 4, cost = 13000, prev = 5699 }, -- Create Healthstone 4
        { id = 11677, level = 46, tab = 3, rank = 3, cost = 13000, prev = 6219 }, -- Rain of Fire 3
        { id = 11712, level = 48, tab = 1, rank = 5, cost = 14000, prev = 11711 }, -- Bane of Agony 5
        { id = 18880, level = 48, tab = 1, rank = 3, cost = 700, prev = 18879, requires = 18265 }, -- Siphon Life 3
        { id = 18647, level = 48, tab = 2, rank = 2, cost = 13000, prev = 710 }, -- Banish 2
        { id = 17727, level = 48, tab = 2, rank = 2, cost = 14000, prev = 2362 }, -- Create Spellstone 2
        { id = 18930, level = 48, tab = 3, rank = 4, cost = 700, prev = 17962, requires = 1293817 }, -- Conflagrate 4
        { id = 18870, level = 48, tab = 3, rank = 5, cost = 700, prev = 18869, requires = 17877 }, -- Shadowburn 5
        { id = 6353, level = 48, tab = 3, rank = 1, cost = 14000 }, -- Soul Fire 1
        { id = 11719, level = 50, tab = 1, rank = 2, cost = 15000, prev = 1714 }, -- Curse of Tongues 2
        { id = 1311680, level = 50, tab = 1, rank = 4, prev = 1311677 }, -- Curse of the Elements 4
        { id = 17925, level = 50, tab = 1, rank = 2, cost = 15000, prev = 6789 }, -- Death Coil 2
        { id = 20756, level = 50, tab = 2, rank = 4, cost = 15000, prev = 20755 }, -- Create Soulstone 4
        { id = 11734, level = 50, tab = 2, rank = 4, cost = 15000, prev = 11733 }, -- Demon Armor 4
        { id = 11743, level = 50, tab = 2, rank = 3, cost = 15000, prev = 2970 }, -- Detect Invisibility 3
        { id = 1122, level = 50, tab = 2, book = 9214 }, -- Inferno
        { id = 11667, level = 50, tab = 3, rank = 6, cost = 15000, prev = 11665 }, -- Immolate 6
        { id = 1293812, level = 50, tab = 3, rank = 2, prev = 412758, requires = 412758 }, -- Incinerate 2
        { id = 17922, level = 50, tab = 3, rank = 5, cost = 15000, prev = 17921 }, -- Searing Pain 5
        { id = 11708, level = 52, tab = 1, rank = 6, cost = 18000, prev = 11707 }, -- Curse of Weakness 6
        { id = 11675, level = 52, tab = 1, rank = 4, cost = 18000, prev = 8289 }, -- Drain Soul 4
        { id = 11694, level = 52, tab = 2, rank = 6, cost = 18000, prev = 11693 }, -- Health Funnel 6
        { id = 11740, level = 52, tab = 2, rank = 3, cost = 18000, prev = 11739 }, -- Shadow Ward 3
        { id = 11660, level = 52, tab = 3, rank = 8, cost = 18000, prev = 11659 }, -- Shadow Bolt 8
        { id = 11672, level = 54, tab = 1, rank = 6, cost = 20000, prev = 11671 }, -- Corruption 6
        { id = 11700, level = 54, tab = 1, rank = 6, cost = 20000, prev = 11699 }, -- Drain Life 6
        { id = 11704, level = 54, tab = 1, rank = 4, cost = 20000, prev = 11703 }, -- Drain Mana 4
        { id = 17928, level = 54, tab = 1, rank = 2, cost = 20000, prev = 5484 }, -- Howl of Terror 2
        { id = 18931, level = 54, tab = 3, rank = 5, cost = 1000, prev = 18930, requires = 1293817 }, -- Conflagrate 5
        { id = 11684, level = 54, tab = 3, rank = 3, cost = 18000, prev = 11683 }, -- Hellfire 3
        { id = 11717, level = 56, tab = 1, rank = 4, cost = 22000, prev = 7659 }, -- Curse of Recklessness 4
        { id = 6215, level = 56, tab = 1, rank = 3, cost = 22000, prev = 6213 }, -- Fear 3
        { id = 11689, level = 56, tab = 1, rank = 6, cost = 22000, prev = 11688 }, -- Life Tap 6
        { id = 17953, level = 56, tab = 2, rank = 4, cost = 22000, prev = 17952 }, -- Create Firestone 4
        { id = 18871, level = 56, tab = 3, rank = 6, cost = 22000, prev = 18870, requires = 17877 }, -- Shadowburn 6
        { id = 17924, level = 56, tab = 3, rank = 2, cost = 22000, prev = 6353 }, -- Soul Fire 2
        { id = 11713, level = 58, tab = 1, rank = 6, cost = 24000, prev = 11712 }, -- Bane of Agony 6
        { id = 17926, level = 58, tab = 1, rank = 3, cost = 24000, prev = 17925 }, -- Death Coil 3
        { id = 18881, level = 58, tab = 1, rank = 4, cost = 1200, prev = 18880, requires = 18265 }, -- Siphon Life 4
        { id = 11730, level = 58, tab = 2, rank = 5, cost = 24000, prev = 11729 }, -- Create Healthstone 5
        { id = 11726, level = 58, tab = 2, rank = 3, cost = 24000, prev = 11725 }, -- Subjugate Demon 3
        { id = 11678, level = 58, tab = 3, rank = 4, cost = 24000, prev = 11677 }, -- Rain of Fire 4
        { id = 17923, level = 58, tab = 3, rank = 6, cost = 24000, prev = 17922 }, -- Searing Pain 6
        { id = 603, level = 60, tab = 1, cost = 26000 }, -- Bane of Doom
        { id = 25311, level = 60, tab = 1, rank = 7, book = 21283, prev = 11672 }, -- Corruption 7
        { id = 20757, level = 60, tab = 2, rank = 5, cost = 26000, prev = 20756 }, -- Create Soulstone 5
        { id = 17728, level = 60, tab = 2, rank = 3, cost = 26000, prev = 17727 }, -- Create Spellstone 3
        { id = 11735, level = 60, tab = 2, rank = 5, cost = 26000, prev = 11734 }, -- Demon Armor 5
        { id = 11695, level = 60, tab = 2, rank = 7, cost = 26000, prev = 11694 }, -- Health Funnel 7
        { id = 18540, level = 60, tab = 2, book = 4213 }, -- Ritual of Doom
        { id = 28610, level = 60, tab = 2, rank = 4, book = 22891, prev = 11740 }, -- Shadow Ward 4
        { id = 18932, level = 60, tab = 3, rank = 6, cost = 1300, prev = 18931, requires = 1293817 }, -- Conflagrate 6
        { id = 11668, level = 60, tab = 3, rank = 7, cost = 26000, prev = 11667 }, -- Immolate 7
        { id = 25309, level = 60, tab = 3, rank = 8, book = 21282, prev = 11668 }, -- Immolate 8
        { id = 1293813, level = 60, tab = 3, rank = 3, prev = 1293812, requires = 412758 }, -- Incinerate 3
        { id = 11661, level = 60, tab = 3, rank = 9, cost = 26000, prev = 11660 }, -- Shadow Bolt 9
        { id = 25307, level = 60, tab = 3, rank = 10, book = 21281, prev = 11661 }, -- Shadow Bolt 10
    },
}
