-- Generated by tools/build_data.py. Do not edit by hand.
-- Forever client build 1.60.1.69876.
local _, SBE = ...

SBE.Data.WARRIOR = {
    tabs = { "Arms", "Fury", "Protection" },
    spells = {
        { id = 6673, level = 1, tab = 2, rank = 1, cost = 10 }, -- Battle Shout 1
        { id = 100, level = 4, tab = 1, rank = 1, cost = 100 }, -- Charge 1
        { id = 772, level = 4, tab = 1, rank = 1, cost = 100 }, -- Rend 1
        { id = 6343, level = 6, tab = 1, rank = 1, cost = 100 }, -- Thunder Clap 1
        { id = 1715, level = 8, tab = 1, rank = 1, cost = 200 }, -- Hamstring 1
        { id = 284, level = 8, tab = 1, rank = 2, cost = 200, prev = 78 }, -- Heroic Strike 2
        { id = 6546, level = 10, tab = 1, rank = 2, cost = 600, prev = 772 }, -- Rend 2
        { id = 2687, level = 10, tab = 3, cost = 600 }, -- Bloodrage
        { id = 71, level = 10, tab = 3, quest = true }, -- Defensive Stance
        { id = 7386, level = 10, tab = 3, rank = 1 }, -- Sunder Armor 1
        { id = 355, level = 10, tab = 3, quest = true }, -- Taunt
        { id = 7384, level = 12, tab = 1, rank = 1, cost = 1000 }, -- Overpower 1
        { id = 5242, level = 12, tab = 2, rank = 2, cost = 1000, prev = 6673 }, -- Battle Shout 2
        { id = 72, level = 12, tab = 3, rank = 1, cost = 1000 }, -- Shield Bash 1
        { id = 1310185, level = 14, tab = 1 }, -- Tactical Mastery
        { id = 1160, level = 14, tab = 2, rank = 1, cost = 1500 }, -- Demoralizing Shout 1
        { id = 6572, level = 14, tab = 3, rank = 1, cost = 1500 }, -- Revenge 1
        { id = 285, level = 16, tab = 1, rank = 3, cost = 2000, prev = 284 }, -- Heroic Strike 3
        { id = 694, level = 16, tab = 1, rank = 1, cost = 2000 }, -- Mocking Blow 1
        { id = 2565, level = 16, tab = 3, cost = 2000 }, -- Shield Block
        { id = 8198, level = 18, tab = 1, rank = 2, cost = 3000, prev = 6343 }, -- Thunder Clap 2
        { id = 676, level = 18, tab = 3, cost = 3000 }, -- Disarm
        { id = 6547, level = 20, tab = 1, rank = 3, cost = 4000, prev = 6546 }, -- Rend 3
        { id = 20230, level = 20, tab = 1, cost = 4000 }, -- Retaliation
        { id = 845, level = 20, tab = 2, rank = 1, cost = 4000 }, -- Cleave 1
        { id = 1240193, level = 20, tab = 2, rank = 1 }, -- Slam 1
        { id = 6192, level = 22, tab = 2, rank = 3, cost = 6000, prev = 5242 }, -- Battle Shout 3
        { id = 5246, level = 22, tab = 2, cost = 6000 }, -- Intimidating Shout
        { id = 7405, level = 22, tab = 3, rank = 2, cost = 6000, prev = 7386 }, -- Sunder Armor 2
        { id = 1608, level = 24, tab = 1, rank = 4, cost = 8000, prev = 285 }, -- Heroic Strike 4
        { id = 6190, level = 24, tab = 2, rank = 2, cost = 8000, prev = 1160 }, -- Demoralizing Shout 2
        { id = 5308, level = 24, tab = 2, rank = 1, cost = 8000 }, -- Execute 1
        { id = 6574, level = 24, tab = 3, rank = 2, cost = 8000, prev = 6572 }, -- Revenge 2
        { id = 6178, level = 26, tab = 1, rank = 2, cost = 10000, prev = 100 }, -- Charge 2
        { id = 7400, level = 26, tab = 1, rank = 2, cost = 10000, prev = 694 }, -- Mocking Blow 2
        { id = 1161, level = 26, tab = 2, cost = 10000 }, -- Challenging Shout
        { id = 7887, level = 28, tab = 1, rank = 2, cost = 11000, prev = 7384 }, -- Overpower 2
        { id = 8204, level = 28, tab = 1, rank = 3, cost = 11000, prev = 8198 }, -- Thunder Clap 3
        { id = 871, level = 28, tab = 3, cost = 11000 }, -- Shield Wall
        { id = 6548, level = 30, tab = 1, rank = 4, cost = 12000, prev = 6547 }, -- Rend 4
        { id = 2458, level = 30, tab = 2, quest = true }, -- Berserker Stance
        { id = 7369, level = 30, tab = 2, rank = 2, cost = 12000, prev = 845 }, -- Cleave 2
        { id = 20252, level = 30, tab = 2, rank = 1 }, -- Intercept 1
        { id = 1464, level = 30, tab = 2, rank = 2, cost = 12000, prev = 1240193 }, -- Slam 2
        { id = 7372, level = 32, tab = 1, rank = 2, cost = 14000, prev = 1715 }, -- Hamstring 2
        { id = 11564, level = 32, tab = 1, rank = 5, cost = 14000, prev = 1608 }, -- Heroic Strike 5
        { id = 11549, level = 32, tab = 2, rank = 4, cost = 14000, prev = 6192 }, -- Battle Shout 4
        { id = 18499, level = 32, tab = 2, cost = 14000 }, -- Berserker Rage
        { id = 20658, level = 32, tab = 2, rank = 2, cost = 14000, prev = 5308 }, -- Execute 2
        { id = 1671, level = 32, tab = 3, rank = 2, cost = 14000, prev = 72 }, -- Shield Bash 2
        { id = 11554, level = 34, tab = 2, rank = 3, cost = 16000, prev = 6190 }, -- Demoralizing Shout 3
        { id = 7379, level = 34, tab = 3, rank = 3, cost = 16000, prev = 6574 }, -- Revenge 3
        { id = 8380, level = 34, tab = 3, rank = 3, cost = 16000, prev = 7405 }, -- Sunder Armor 3
        { id = 7402, level = 36, tab = 1, rank = 3, cost = 18000, prev = 7400 }, -- Mocking Blow 3
        { id = 1680, level = 36, tab = 2, cost = 18000 }, -- Whirlwind
        { id = 8205, level = 38, tab = 1, rank = 4, cost = 20000, prev = 8204 }, -- Thunder Clap 4
        { id = 6552, level = 38, tab = 2, rank = 1, cost = 20000 }, -- Pummel 1
        { id = 8820, level = 38, tab = 2, rank = 3, cost = 20000, prev = 1464 }, -- Slam 3
        { id = 11565, level = 40, tab = 1, rank = 6, cost = 22000, prev = 11564 }, -- Heroic Strike 6
        { id = 11572, level = 40, tab = 1, rank = 5, cost = 22000, prev = 6548 }, -- Rend 5
        { id = 11608, level = 40, tab = 2, rank = 3, cost = 22000, prev = 7369 }, -- Cleave 3
        { id = 20660, level = 40, tab = 2, rank = 3, cost = 22000, prev = 20658 }, -- Execute 3
        { id = 11550, level = 42, tab = 2, rank = 5, cost = 32000, prev = 11549 }, -- Battle Shout 5
        { id = 20616, level = 42, tab = 2, rank = 2, prev = 20252 }, -- Intercept 2
        { id = 11584, level = 44, tab = 1, rank = 3, cost = 34000, prev = 7887 }, -- Overpower 3
        { id = 11555, level = 44, tab = 2, rank = 4, cost = 34000, prev = 11554 }, -- Demoralizing Shout 4
        { id = 11600, level = 44, tab = 3, rank = 4, cost = 34000, prev = 7379 }, -- Revenge 4
        { id = 11578, level = 46, tab = 1, rank = 3, cost = 36000, prev = 6178 }, -- Charge 3
        { id = 20559, level = 46, tab = 1, rank = 4, cost = 36000, prev = 7402 }, -- Mocking Blow 4
        { id = 11604, level = 46, tab = 2, rank = 4, cost = 36000, prev = 8820 }, -- Slam 4
        { id = 11596, level = 46, tab = 3, rank = 4, cost = 36000, prev = 8380 }, -- Sunder Armor 4
        { id = 11566, level = 48, tab = 1, rank = 7, cost = 40000, prev = 11565 }, -- Heroic Strike 7
        { id = 21551, level = 48, tab = 1, rank = 2, cost = 200, prev = 12294, requires = 12294 }, -- Mortal Strike 2
        { id = 11580, level = 48, tab = 1, rank = 5, cost = 40000, prev = 8205 }, -- Thunder Clap 5
        { id = 23892, level = 48, tab = 2, rank = 2, cost = 2000, prev = 23881, requires = 23881 }, -- Bloodthirst 2
        { id = 20661, level = 48, tab = 2, rank = 4, cost = 40000, prev = 20660 }, -- Execute 4
        { id = 23923, level = 48, tab = 3, rank = 2, cost = 200, prev = 23922, requires = 23922 }, -- Shield Slam 2
        { id = 11573, level = 50, tab = 1, rank = 6, cost = 42000, prev = 11572 }, -- Rend 6
        { id = 11609, level = 50, tab = 2, rank = 4, cost = 42000, prev = 11608 }, -- Cleave 4
        { id = 1719, level = 50, tab = 2, cost = 42000 }, -- Recklessness
        { id = 11551, level = 52, tab = 2, rank = 6, cost = 54000, prev = 11550 }, -- Battle Shout 6
        { id = 20617, level = 52, tab = 2, rank = 3, prev = 20616 }, -- Intercept 3
        { id = 1672, level = 52, tab = 3, rank = 3, cost = 54000, prev = 1671 }, -- Shield Bash 3
        { id = 7373, level = 54, tab = 1, rank = 3, cost = 56000, prev = 7372 }, -- Hamstring 3
        { id = 21552, level = 54, tab = 1, rank = 3, cost = 2800, prev = 21551, requires = 12294 }, -- Mortal Strike 3
        { id = 23893, level = 54, tab = 2, rank = 3, cost = 2800, prev = 23892, requires = 23881 }, -- Bloodthirst 3
        { id = 11556, level = 54, tab = 2, rank = 5, cost = 56000, prev = 11555 }, -- Demoralizing Shout 5
        { id = 11605, level = 54, tab = 2, rank = 5, cost = 56000, prev = 11604 }, -- Slam 5
        { id = 11601, level = 54, tab = 3, rank = 5, cost = 56000, prev = 11600 }, -- Revenge 5
        { id = 23924, level = 54, tab = 3, rank = 3, cost = 2800, prev = 23923, requires = 23922 }, -- Shield Slam 3
        { id = 11567, level = 56, tab = 1, rank = 8, cost = 58000, prev = 11566 }, -- Heroic Strike 8
        { id = 20560, level = 56, tab = 1, rank = 5, cost = 58000, prev = 20559 }, -- Mocking Blow 5
        { id = 20662, level = 56, tab = 2, rank = 5, cost = 58000, prev = 20661 }, -- Execute 5
        { id = 11581, level = 58, tab = 1, rank = 6, cost = 60000, prev = 11580 }, -- Thunder Clap 6
        { id = 6554, level = 58, tab = 2, rank = 2, cost = 60000, prev = 6552 }, -- Pummel 2
        { id = 11597, level = 58, tab = 3, rank = 5, cost = 60000, prev = 11596 }, -- Sunder Armor 5
        { id = 25286, level = 60, tab = 1, rank = 9, book = 21297, prev = 11567 }, -- Heroic Strike 9
        { id = 21553, level = 60, tab = 1, rank = 4, cost = 3100, prev = 21552, requires = 12294 }, -- Mortal Strike 4
        { id = 11585, level = 60, tab = 1, rank = 4, cost = 62000, prev = 11584 }, -- Overpower 4
        { id = 11574, level = 60, tab = 1, rank = 7, cost = 62000, prev = 11573 }, -- Rend 7
        { id = 25289, level = 60, tab = 2, rank = 7, book = 21298, prev = 11551 }, -- Battle Shout 7
        { id = 23894, level = 60, tab = 2, rank = 4, cost = 3100, prev = 23893, requires = 23881 }, -- Bloodthirst 4
        { id = 20569, level = 60, tab = 2, rank = 5, cost = 62000, prev = 11609 }, -- Cleave 5
        { id = 25288, level = 60, tab = 3, rank = 6, book = 21299, prev = 11601 }, -- Revenge 6
        { id = 23925, level = 60, tab = 3, rank = 4, cost = 3100, prev = 23924, requires = 23922 }, -- Shield Slam 4
    },
}
